#include <clib/macros.h>
#include <clib/alib_protos.h>
#include <clib/compiler-specific.h>

#include <proto/exec.h>
#include <proto/dos.h>
#include <proto/utility.h>
#include <proto/graphics.h>
#include <proto/intuition.h>
#include <proto/gadtools.h>
#include <proto/icon.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <proto/window.h>
#include <proto/layout.h>
#include <proto/button.h>
#include <proto/chooser.h>
#include <proto/listbrowser.h>
#include <proto/label.h>

#include <libraries/gadtools.h>
#include <reaction/reaction.h>
#include <intuition/gadgetclass.h>
#include <intuition/icclass.h>
#include <reaction/reaction_macros.h>
#include <classes/window.h>
#include <exec/memory.h>

void deficons_text_templates( void );

struct Screen	*gScreen = NULL;
struct DrawInfo	*gDrawInfo = NULL;
APTR gVisinfo = NULL;
struct MsgPort	*gAppPort = NULL;

struct Library *WindowBase = NULL,
               *ButtonBase = NULL,
               *ChooserBase = NULL,
               *ListBrowserBase = NULL,
               *LabelBase = NULL,
               *GadToolsBase = NULL,
               *LayoutBase = NULL,
               *IconBase = NULL;
struct IntuitionBase *IntuitionBase = NULL;

//window ids
enum win { deficons_text_templates_id = 4 };

//defIcons_text_templates gadgets
enum deficons_text_templates_idx { vert_6, vert_8, horiz_10, vert_11, deficons_text_show_chooser, 
  deficons_text_templates_listbrowser, vert_12, vert_21, vert_36, 
  deficons_text_selected_type_value, vert_37, deficons_text_selected_templatefile_value, 
  vert_38, deficons_text_selected_effective_value, vert_39, deficons_text_selected_status_value, 
  vert_40, vert_22, deficons_text_btn_create_overwrite_master, 
  deficons_text_btn_edit_tooltypes, deficons_text_btn_validate_tooltypes, 
  deficons_text_btn_revert_to_master, horiz_30, vert_31, horiz_32, 
  button_33 };
enum deficons_text_templates_id { vert_6_id = 6, vert_8_id = 8, horiz_10_id = 10, vert_11_id = 11, 
  deficons_text_show_chooser_id = 9, deficons_text_templates_listbrowser_id = 13, 
  vert_12_id = 12, vert_21_id = 21, vert_36_id = 36, deficons_text_selected_type_value_id = 16, 
  vert_37_id = 37, deficons_text_selected_templatefile_value_id = 17, 
  vert_38_id = 38, deficons_text_selected_effective_value_id = 19, 
  vert_39_id = 39, deficons_text_selected_status_value_id = 20, 
  vert_40_id = 40, vert_22_id = 22, deficons_text_btn_create_overwrite_master_id = 24, 
  deficons_text_btn_edit_tooltypes_id = 25, deficons_text_btn_validate_tooltypes_id = 26, 
  deficons_text_btn_revert_to_master_id = 35, horiz_30_id = 30, 
  vert_31_id = 31, horiz_32_id = 32, button_33_id = 33 };

void deficons_text_templates( void )
{
  struct Gadget	*main_gadgets[ 27 ];
  Object *window_object = NULL;
  struct HintInfo hintInfo[] =
  {
    {vert_6_id,-1,"",0},
    {vert_8_id,-1,"",0},
    {horiz_10_id,-1,"",0},
    {vert_11_id,-1,"",0},
    {deficons_text_show_chooser_id,-1,"Choose which template types to show in the list (All, Custom only, or Using master).",0},
    {deficons_text_templates_listbrowser_id,-1,"Select a file type to see which template icon it uses and to manage its template.",0},
    {vert_12_id,-1,"",0},
    {vert_21_id,-1,"",0},
    {vert_36_id,-1,"",0},
    {deficons_text_selected_type_value_id,-1,"The file type currently selected in the list.",0},
    {vert_37_id,-1,"",0},
    {deficons_text_selected_templatefile_value_id,-1,"The custom template icon file for this type, if one exists.",0},
    {vert_38_id,-1,"",0},
    {deficons_text_selected_effective_value_id,-1,"The template icon that will actually be used (custom template, or the master template if none exists).",0},
    {vert_39_id,-1,"",0},
    {deficons_text_selected_status_value_id,-1,"Shows whether this type uses a custom template or falls back to the master template.",0},
    {vert_40_id,-1,"",0},
    {vert_22_id,-1,"",0},
    {deficons_text_btn_create_overwrite_master_id,-1,"Create a custom template for the selected type by copying the master template. If a custom template already exists, it will be overwritten.",0},
    {deficons_text_btn_edit_tooltypes_id,-1,"Open the selected template in Workbench Information so you can edit ToolTypes. Changes are saved by Workbench when you click Save.",0},
    {deficons_text_btn_validate_tooltypes_id,-1,"Check the selected template's ToolTypes for common mistakes and report any issues found.",0},
    {deficons_text_btn_revert_to_master_id,-1,"Remove the custom template for the selected type so it uses the master template again. This deletes the type's template icon file.",0},
    {horiz_30_id,-1,"",0},
    {vert_31_id,-1,"",0},
    {horiz_32_id,-1,"",0},
    {button_33_id,-1,"",0},
    {-1,-1,NULL,0}
  };
  struct List *labels9;
  UBYTE *labels9_str[] = { "All", "Custom only", "Missing only",  NULL };
  struct List *labels13;
  UBYTE *labels13_str[] = { NULL };
  labels9 = ChooserLabelsA( labels9_str );
  labels13 = BrowserNodesA( labels13_str, 1 );

  window_object = NewObject( WINDOW_GetClass(), NULL, 
    WA_Title, "DefIcons: Text Templates   ",
    WA_Left, 5,
    WA_Top, 20,
    WA_Width, 150,
    WA_Height, 80,
    WA_MinWidth, 150,
    WA_MinHeight, 80,
    WA_MaxWidth, 8192,
    WA_MaxHeight, 8192,
    WINDOW_HintInfo, hintInfo,
    WINDOW_GadgetHelp, TRUE,
    WINDOW_AppPort, gAppPort,
    WA_CloseGadget, TRUE,
    WA_DepthGadget, TRUE,
    WA_SizeGadget, TRUE,
    WA_DragBar, TRUE,
    WA_Activate, TRUE,
    WINDOW_IconTitle, "MyApp",
    WA_NoCareRefresh, TRUE,
    WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_NEWSIZE,
    WINDOW_ParentGroup, NewObject( LAYOUT_GetClass(), NULL,
    LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
    LAYOUT_SpaceOuter, TRUE,
    LAYOUT_DeferLayout, TRUE,
      LAYOUT_AddChild, main_gadgets[vert_6] = NewObject( LAYOUT_GetClass(), NULL, 
        GA_ID, vert_6_id,
        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
        LAYOUT_LeftSpacing, 4,
        LAYOUT_RightSpacing, 4,
        LAYOUT_TopSpacing, 4,
        LAYOUT_BottomSpacing, 4,
        LAYOUT_AddChild, main_gadgets[vert_8] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, vert_8_id,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_AddChild, main_gadgets[horiz_10] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, horiz_10_id,
            LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
            LAYOUT_AddChild, main_gadgets[vert_11] = NewObject( LAYOUT_GetClass(), NULL, 
              GA_ID, vert_11_id,
              LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_BevelStyle, BVS_FIELD,
              LAYOUT_LeftSpacing, 2,
              LAYOUT_RightSpacing, 2,
              LAYOUT_TopSpacing, 2,
              LAYOUT_BottomSpacing, 4,
              LAYOUT_Label, "Icons",
              LAYOUT_AddChild, main_gadgets[deficons_text_show_chooser] = NewObject( CHOOSER_GetClass(), NULL, 
                GA_ID, deficons_text_show_chooser_id,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHOOSER_PopUp, TRUE,
                CHOOSER_Selected, 0,
                CHOOSER_Labels, labels9,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Show",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[deficons_text_templates_listbrowser] = NewObject( LISTBROWSER_GetClass(), NULL, 
                GA_ID, deficons_text_templates_listbrowser_id,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                LISTBROWSER_Position, 0,
              TAG_END),
            TAG_END),
            CHILD_WeightedWidth, 65,
            LAYOUT_AddChild, main_gadgets[vert_12] = NewObject( LAYOUT_GetClass(), NULL, 
              GA_ID, vert_12_id,
              LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_LeftSpacing, 4,
              LAYOUT_AddChild, main_gadgets[vert_21] = NewObject( LAYOUT_GetClass(), NULL, 
                GA_ID, vert_21_id,
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_BevelStyle, BVS_FIELD,
                LAYOUT_LeftSpacing, 2,
                LAYOUT_RightSpacing, 2,
                LAYOUT_TopSpacing, 2,
                LAYOUT_BottomSpacing, 2,
                LAYOUT_Label, "Selected Type",
                LAYOUT_AddChild, main_gadgets[vert_36] = NewObject( LAYOUT_GetClass(), NULL, 
                  GA_ID, vert_36_id,
                  LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                  LAYOUT_AddChild, main_gadgets[deficons_text_selected_type_value] = NewObject( BUTTON_GetClass(), NULL, 
                    GA_ID, deficons_text_selected_type_value_id,
                    GA_Text, "Rexx",
                    GA_RelVerify, TRUE,
                    GA_TabCycle, TRUE,
                    BUTTON_Transparent, TRUE,
                    BUTTON_TextPen, 1,
                    BUTTON_BackgroundPen, 0,
                    BUTTON_FillTextPen, 1,
                    BUTTON_FillPen, 3,
                    BUTTON_BevelStyle, BVS_NONE,
                    BUTTON_Justification, BCJ_LEFT,
                  TAG_END),
                  CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                    LABEL_Text, "Type:",
                  TAG_END),
                TAG_END),
                LAYOUT_AddChild, main_gadgets[vert_37] = NewObject( LAYOUT_GetClass(), NULL, 
                  GA_ID, vert_37_id,
                  LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                  LAYOUT_AddChild, main_gadgets[deficons_text_selected_templatefile_value] = NewObject( BUTTON_GetClass(), NULL, 
                    GA_ID, deficons_text_selected_templatefile_value_id,
                    GA_Text, "Progdir:...",
                    GA_RelVerify, TRUE,
                    GA_TabCycle, TRUE,
                    BUTTON_Transparent, TRUE,
                    BUTTON_TextPen, 1,
                    BUTTON_BackgroundPen, 0,
                    BUTTON_FillTextPen, 1,
                    BUTTON_FillPen, 3,
                    BUTTON_BevelStyle, BVS_NONE,
                    BUTTON_Justification, BCJ_LEFT,
                  TAG_END),
                  CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                    LABEL_Text, "Template file:",
                  TAG_END),
                TAG_END),
                LAYOUT_AddChild, main_gadgets[vert_38] = NewObject( LAYOUT_GetClass(), NULL, 
                  GA_ID, vert_38_id,
                  LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                  LAYOUT_AddChild, main_gadgets[deficons_text_selected_effective_value] = NewObject( BUTTON_GetClass(), NULL, 
                    GA_ID, deficons_text_selected_effective_value_id,
                    GA_Text, "Progdir:...",
                    GA_RelVerify, TRUE,
                    GA_TabCycle, TRUE,
                    BUTTON_Transparent, TRUE,
                    BUTTON_TextPen, 1,
                    BUTTON_BackgroundPen, 0,
                    BUTTON_FillTextPen, 1,
                    BUTTON_FillPen, 3,
                    BUTTON_BevelStyle, BVS_NONE,
                    BUTTON_Justification, BCJ_LEFT,
                  TAG_END),
                  CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                    LABEL_Text, "Effective:",
                  TAG_END),
                TAG_END),
                LAYOUT_AddChild, main_gadgets[vert_39] = NewObject( LAYOUT_GetClass(), NULL, 
                  GA_ID, vert_39_id,
                  LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                  LAYOUT_AddChild, main_gadgets[deficons_text_selected_status_value] = NewObject( BUTTON_GetClass(), NULL, 
                    GA_ID, deficons_text_selected_status_value_id,
                    GA_Text, "Custom",
                    GA_RelVerify, TRUE,
                    GA_TabCycle, TRUE,
                    BUTTON_Transparent, TRUE,
                    BUTTON_TextPen, 1,
                    BUTTON_BackgroundPen, 0,
                    BUTTON_FillTextPen, 1,
                    BUTTON_FillPen, 3,
                    BUTTON_BevelStyle, BVS_NONE,
                    BUTTON_Justification, BCJ_LEFT,
                  TAG_END),
                  CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                    LABEL_Text, "Status:",
                  TAG_END),
                TAG_END),
              TAG_END),
              LAYOUT_AddChild, main_gadgets[vert_40] = NewObject( LAYOUT_GetClass(), NULL, 
                GA_ID, vert_40_id,
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              TAG_END),
              CHILD_MinHeight, 5,
              CHILD_MaxHeight, 5,
              LAYOUT_AddChild, main_gadgets[vert_22] = NewObject( LAYOUT_GetClass(), NULL, 
                GA_ID, vert_22_id,
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_BevelStyle, BVS_FIELD,
                LAYOUT_LeftSpacing, 2,
                LAYOUT_RightSpacing, 2,
                LAYOUT_TopSpacing, 2,
                LAYOUT_BottomSpacing, 4,
                LAYOUT_Label, "Template action",
                LAYOUT_AddChild, main_gadgets[deficons_text_btn_create_overwrite_master] = NewObject( BUTTON_GetClass(), NULL, 
                  GA_ID, deficons_text_btn_create_overwrite_master_id,
                  GA_Text, "Create from master",
                  GA_RelVerify, TRUE,
                  GA_TabCycle, TRUE,
                  BUTTON_TextPen, 1,
                  BUTTON_BackgroundPen, 0,
                  BUTTON_FillTextPen, 1,
                  BUTTON_FillPen, 3,
                TAG_END),
                LAYOUT_AddChild, main_gadgets[deficons_text_btn_edit_tooltypes] = NewObject( BUTTON_GetClass(), NULL, 
                  GA_ID, deficons_text_btn_edit_tooltypes_id,
                  GA_Text, "Edit tooltypes...",
                  GA_RelVerify, TRUE,
                  GA_TabCycle, TRUE,
                  BUTTON_TextPen, 1,
                  BUTTON_BackgroundPen, 0,
                  BUTTON_FillTextPen, 1,
                  BUTTON_FillPen, 3,
                TAG_END),
                LAYOUT_AddChild, main_gadgets[deficons_text_btn_validate_tooltypes] = NewObject( BUTTON_GetClass(), NULL, 
                  GA_ID, deficons_text_btn_validate_tooltypes_id,
                  GA_Text, "Validate tooltypes",
                  GA_RelVerify, TRUE,
                  GA_TabCycle, TRUE,
                  BUTTON_TextPen, 1,
                  BUTTON_BackgroundPen, 0,
                  BUTTON_FillTextPen, 1,
                  BUTTON_FillPen, 3,
                TAG_END),
                LAYOUT_AddChild, main_gadgets[deficons_text_btn_revert_to_master] = NewObject( BUTTON_GetClass(), NULL, 
                  GA_ID, deficons_text_btn_revert_to_master_id,
                  GA_Text, "Revert to master",
                  GA_RelVerify, TRUE,
                  GA_TabCycle, TRUE,
                  BUTTON_TextPen, 1,
                  BUTTON_BackgroundPen, 0,
                  BUTTON_FillTextPen, 1,
                  BUTTON_FillPen, 3,
                TAG_END),
              TAG_END),
            TAG_END),
            CHILD_WeightedWidth, 35,
          TAG_END),
          CHILD_WeightedHeight, 95,
        TAG_END),
        LAYOUT_AddChild, main_gadgets[horiz_30] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, horiz_30_id,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_TopSpacing, 10,
          LAYOUT_AddChild, main_gadgets[vert_31] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, vert_31_id,
            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          TAG_END),
          CHILD_WeightedWidth, 65,
          LAYOUT_AddChild, main_gadgets[horiz_32] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, horiz_32_id,
            LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
            LAYOUT_LeftSpacing, 4,
            LAYOUT_AddChild, main_gadgets[button_33] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, button_33_id,
              GA_Text, "Close",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
            TAG_END),
          TAG_END),
          CHILD_WeightedWidth, 35,
        TAG_END),
        CHILD_WeightedHeight, 5,
      TAG_END),
    TAG_END),
  TAG_END);  
  main_gadgets[26] = 0;
}

