#include <clib/macros.h>
#include <clib/alib_protos.h>
#include <clib/compiler-specific.h>

#include <proto/exec.h>
#include <proto/dos.h>
#include <proto/utility.h>
#include <proto/graphics.h>
#include <proto/intuition.h>
#include <proto/gadtools.h>
#include <proto/icon.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <proto/window.h>
#include <proto/layout.h>
#include <proto/button.h>
#include <proto/checkbox.h>
#include <proto/chooser.h>
#include <proto/clicktab.h>
#include <proto/fuelgauge.h>
#include <proto/getfile.h>
#include <proto/integer.h>
#include <proto/listbrowser.h>
#include <proto/space.h>
#include <proto/label.h>
#include <gadgets/listview.h>
#include <pragmas/listview_pragmas.h>

#include <libraries/gadtools.h>
#include <reaction/reaction.h>
#include <intuition/gadgetclass.h>
#include <intuition/icclass.h>
#include <reaction/reaction_macros.h>
#include <classes/window.h>
#include <exec/memory.h>

void main_window( void );
void main_progress_window( void );
void advanced_settings( void );
void restore_backups( void );
void restore_folders_view( void );
void recursive_progress_window( void );
void default_tool_analysis( void );
void default_tool_update( void );
void restore_default_tool( void );

struct Screen	*gScreen = NULL;
struct DrawInfo	*gDrawInfo = NULL;
APTR gVisinfo = NULL;
struct MsgPort	*gAppPort = NULL;

struct Library *WindowBase = NULL,
               *ButtonBase = NULL,
               *CheckBoxBase = NULL,
               *ChooserBase = NULL,
               *ClickTabBase  = NULL,
               *FuelGaugeBase = NULL,
               *GetFileBase = NULL,
               *IntegerBase = NULL,
               *ListBrowserBase = NULL,
               *SpaceBase = NULL,
               *LabelBase = NULL,
               *ListViewBase = NULL,
               *GadToolsBase = NULL,
               *LayoutBase = NULL,
               *IconBase = NULL;
struct IntuitionBase *IntuitionBase = NULL;

//window ids
enum win { main_window_id = 4, main_progress_window_id = 53, advanced_settings_id = 59, 
  restore_backups_id = 103, restore_folders_view_id = 118, recursive_progress_window_id = 123, 
  default_tool_analysis_id = 132, default_tool_update_id = 152, 
  restore_default_tool_id = 180 };

//main_window gadgets
enum main_window_idx { master_layout, folder_layout, folder_name, itidy_options, left_column, 
  order_selection, cleanup_subfolders, position_selector, right_column, 
  order_by_selection, backup_icons_checkbox, help_button, tools_layout, 
  advanced_button, default_tools_button, restore_backups_button, 
  main_buttons_layout, start_button, exit_button };
//main_progress_window gadgets
enum main_progress_window_idx { status_container, status_list_container, progress_listbrowser, 
  status_sub_text, slow_progress_text, status_buttons_layout, progress_cancel_button };
//advanced_settings gadgets
enum advanced_settings_idx { vert_61, advanced_tab, advanced_tab_layout, advanced_layout_aspect, 
  advanced_layout_full, advanced_layout_align_vertically, advanced_tab_density, 
  advanced_iconspacing_x, advanced_iconspacing_y, space_251, advanced_tab_limits, 
  advanced_icons_per_row, advanced_icons_per_row_autolayout, advanced_icons_per_row_max, 
  advanced_layout_width, advanced_tab_columns_and_groups, advanced_layout_column_layout, 
  advanced_layout_gap_between_groups, space_258, advanced_tab_filters_and_misc, 
  advanced_layout_skip_hidden, advanced_layout_strip_newicon_borders, 
  advanced_layout_reverse_sort, advanced_layout_opitimze_columns, 
  advanced_layout_main_buttons, advanced_buttons_col1, advanced_buttons_col2, 
  advanced_defaults_button, advanced_cancel_button, advanced_ok_button };
//restore_backups gadgets
enum restore_backups_idx { vert_105, backup_list_layout, backup_list, backup_details_layout, 
  details_browser, backup_buttons_row1_layout, backup_delete_run, 
  backup_restore_run, backup_view_folders, button_cancel };
//restore_folders_view gadgets
enum restore_folders_view_idx { vert_120, folder_browser, close_button };
//recursive_progress_window gadgets
enum recursive_progress_window_idx { vert_125, main_progress_bar, main_progress_label, sub_progress_bar, 
  sub_process_label };
//default_tool_analysis gadgets
enum default_tool_analysis_idx { vert_134, tool_folder_location, tools_folder_name, scan_button, 
  tool_details_layout, tools_filter, tool_status_list, tool_status_layout, 
  tool_status_listview, tool_status_buttons, tool_status_layout_col1, 
  replace_tool_batch, resore_default_tools_backup, tool_status_layout_col2, 
  replace_tool_single, tools_close_button };
//default_tool_update gadgets
enum default_tool_update_idx { vert_154, current_tool_layout_horizontal, current_tool_layout_col1, 
  label_current_tool, mode_text, change_to_label2, current_tool_layout_col2, 
  current_tool_text, current_mode_text, default_tool_new_tool, 
  update_progress_listview, update_progress_label, listview_update_progress, 
  default_tool_buttons, default_tool_update_button, update_tool_close };
//restore_default_tool gadgets
enum restore_default_tool_idx { vert_182, backup_session_layout, restore_listbrowser_label, backup_sessions_listbrowser, 
  tool_changes_sesssion, tool_changes_label, tool_changes_listbroswer, 
  restore_tools_buttons, restore_tools_restore_button, restore_tools_delete_button, 
  restore_tools_close_button };

void main_window( void )
{
  struct NewMenu menuData[] =
  {
    { NM_TITLE, "Project", 0, 0, 0, NULL },
    { NM_ITEM, "New", "N", 0, 510, NULL },
    { NM_ITEM, "Open...", "O", 0, 509, NULL },
    { NM_ITEM, NM_BARLABEL, 0, 0, 507, NULL },
    { NM_ITEM, "Save...", "S", 0, 503, NULL },
    { NM_ITEM, "Save as", "A", 0, 495, NULL },
    { NM_ITEM, NM_BARLABEL, 0, 0, 479, NULL },
    { NM_ITEM, "About", 0, 0, 447, NULL },
    { NM_ITEM, NM_BARLABEL, 0, 0, 383, NULL },
    { NM_ITEM, "Quit", 0, 0, 255, NULL },
    { NM_END, NULL, 0, 0, 0, (APTR)0 }
  };

  struct Menu	*menu_strip = NULL;
  struct Gadget	*main_gadgets[ 20 ];
  Object *window_object = NULL;
  struct HintInfo hintInfo[] =
  {
    {master_layout,-1,"",0},
    {folder_layout,-1,"",0},
    {folder_name,-1,"Select the folder you want to tidy. To include subfolders, enable 'Include subfolders' below.",0},
    {itidy_options,-1,"",0},
    {left_column,-1,"",0},
    {order_selection,-1,"Sets how icons are grouped before sorting. Folders first, files first, mixed, or grouped by type.",0},
    {cleanup_subfolders,-1,"When enabled, iTidy also processes all subfolders under the selected folder.",0},
    {position_selector,-1,"Controls where drawer windows are placed after resizing. (Only affects windows iTidy changes.)",0},
    {right_column,-1,"",0},
    {order_by_selection,-1,"Selects the field used for sorting: name, kind, date, or size.",0},
    {backup_icons_checkbox,-1,"Creates an LhA backup of the folder's .info files before changes. Requires LhA in C: (or on your PATH).",0},
    {help_button,-1,"",0},
    {tools_layout,-1,"",0},
    {advanced_button,-1,"Opens Advanced Settings for finer control over layout and sizing.",0},
    {default_tools_button,-1,"Scans icons for missing or invalid default tools. Lets you fix them, or batch-replace one tool with another",0},
    {restore_backups_button,-1,"Restores icon positions and window snapshots from iTidy backups. Only available if you previously enabled backups.",0},
    {main_buttons_layout,-1,"",0},
    {start_button,-1,"Starts tidying the selected folder using the current settings.",0},
    {exit_button,-1,"Closes iTidy.",0},
    {-1,-1,NULL,0}
  };
  struct List *labels35;
  UBYTE *labels35_str[] = { "Folders first", "Files first", "Mixed", "Grouped by type",  NULL };
  struct List *labels37;
  UBYTE *labels37_str[] = { "Center screen", "Keep position", "Near parent", "No change",  NULL };
  struct List *labels38;
  UBYTE *labels38_str[] = { "Name", "Type", "Date", "Size",  NULL };
  menu_strip = CreateMenusA( menuData, TAG_END );
  LayoutMenus( menu_strip, gVisinfo,
    GTMN_NewLookMenus, TRUE,
    TAG_DONE );

  labels35 = ChooserLabelsA( labels35_str );
  labels37 = ChooserLabelsA( labels37_str );
  labels38 = ChooserLabelsA( labels38_str );

  window_object = NewObject( WINDOW_GetClass(), NULL, 
    WA_Title, "iTidy - Icon cleanup tool",
    WA_Left, 5,
    WA_Top, 20,
    WA_Width, 150,
    WA_Height, 80,
    WA_MinWidth, 150,
    WA_MinHeight, 80,
    WA_MaxWidth, 8192,
    WA_MaxHeight, 8192,
    WINDOW_HintInfo, hintInfo,
    WINDOW_GadgetHelp, TRUE,
    WINDOW_AppPort, gAppPort,
    WA_CloseGadget, TRUE,
    WA_DepthGadget, TRUE,
    WA_SizeGadget, TRUE,
    WA_DragBar, TRUE,
    WA_Activate, TRUE,
    WINDOW_Position, WPOS_CENTERMOUSE,
    WINDOW_IconTitle, "MyApp",
    WA_NoCareRefresh, TRUE,
    WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_MENUPICK | IDCMP_MENUHELP | IDCMP_NEWSIZE,
    WINDOW_ParentGroup, NewObject( LAYOUT_GetClass(), NULL,
    LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
    LAYOUT_SpaceOuter, TRUE,
    LAYOUT_DeferLayout, TRUE,
      LAYOUT_AddChild, main_gadgets[master_layout] = NewObject( LAYOUT_GetClass(), NULL, 
        GA_ID, master_layout,
        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
        LAYOUT_LeftSpacing, 2,
        LAYOUT_RightSpacing, 2,
        LAYOUT_TopSpacing, 2,
        LAYOUT_BottomSpacing, 2,
        LAYOUT_AddChild, main_gadgets[folder_layout] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, folder_layout,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_BevelStyle, BVS_THIN,
          LAYOUT_LeftSpacing, 2,
          LAYOUT_RightSpacing, 2,
          LAYOUT_TopSpacing, 3,
          LAYOUT_BottomSpacing, 4,
          LAYOUT_AddChild, main_gadgets[folder_name] = NewObject( GETFILE_GetClass(), NULL, 
            GA_ID, folder_name,
            GA_RelVerify, TRUE,
            GETFILE_TitleText, "Select a file",
            GETFILE_Drawer, "folder_name_string",
            GETFILE_FullFile, "Sys:",
            GETFILE_FilterDrawers, TRUE,
            GETFILE_ReadOnly, TRUE,
          TAG_END),
          CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
            LABEL_Text, "Folder to tidy",
          TAG_END),
        TAG_END),
        LAYOUT_AddChild, main_gadgets[itidy_options] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, itidy_options,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_BevelStyle, BVS_THIN,
          LAYOUT_LeftSpacing, 2,
          LAYOUT_RightSpacing, 2,
          LAYOUT_TopSpacing, 2,
          LAYOUT_BottomSpacing, 4,
          LAYOUT_AddChild, main_gadgets[left_column] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, left_column,
            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
            LAYOUT_RightSpacing, 2,
            LAYOUT_AddChild, main_gadgets[order_selection] = NewObject( CHOOSER_GetClass(), NULL, 
              GA_ID, order_selection,
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              CHOOSER_PopUp, TRUE,
              CHOOSER_Selected, 0,
              CHOOSER_Labels, labels35,
            TAG_END),
            CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
              LABEL_Text, "Grouping",
            TAG_END),
            LAYOUT_AddChild, main_gadgets[cleanup_subfolders] = NewObject( CHECKBOX_GetClass(), NULL, 
              GA_ID, cleanup_subfolders,
              GA_Text, "",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              CHECKBOX_TextPlace, PLACETEXT_RIGHT,
            TAG_END),
            CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
              LABEL_Text, "Include subfolders",
            TAG_END),
            LAYOUT_AddChild, main_gadgets[position_selector] = NewObject( CHOOSER_GetClass(), NULL, 
              GA_ID, position_selector,
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              CHOOSER_PopUp, TRUE,
              CHOOSER_Selected, 0,
              CHOOSER_Labels, labels37,
            TAG_END),
            CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
              LABEL_Text, "Window position",
            TAG_END),
          TAG_END),
          LAYOUT_AddChild, main_gadgets[right_column] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, right_column,
            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
            LAYOUT_LeftSpacing, 2,
            LAYOUT_AddChild, main_gadgets[order_by_selection] = NewObject( CHOOSER_GetClass(), NULL, 
              GA_ID, order_by_selection,
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              CHOOSER_PopUp, TRUE,
              CHOOSER_Selected, 0,
              CHOOSER_Labels, labels38,
            TAG_END),
            CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
              LABEL_Text, "Sort by",
            TAG_END),
            LAYOUT_AddChild, main_gadgets[backup_icons_checkbox] = NewObject( CHECKBOX_GetClass(), NULL, 
              GA_ID, backup_icons_checkbox,
              GA_Text, "",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              CHECKBOX_TextPlace, PLACETEXT_RIGHT,
            TAG_END),
            CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
              LABEL_Text, "Backup layouts",
            TAG_END),
            LAYOUT_AddChild, main_gadgets[help_button] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, help_button,
              GA_Text, "?",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
            TAG_END),
            CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
              LABEL_Text, "Hints",
            TAG_END),
          TAG_END),
        TAG_END),
        LAYOUT_AddChild, main_gadgets[tools_layout] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, tools_layout,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_BevelStyle, BVS_THIN,
          LAYOUT_LeftSpacing, 2,
          LAYOUT_RightSpacing, 2,
          LAYOUT_TopSpacing, 2,
          LAYOUT_BottomSpacing, 4,
          LAYOUT_AddChild, main_gadgets[advanced_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, advanced_button,
            GA_Text, "Advanced...",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[default_tools_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, default_tools_button,
            GA_Text, "Fix default tools...",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[restore_backups_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, restore_backups_button,
            GA_Text, "Restore backups...",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
        TAG_END),
        LAYOUT_AddChild, main_gadgets[main_buttons_layout] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, main_buttons_layout,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_AddChild, main_gadgets[start_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, start_button,
            GA_Text, "Start",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[exit_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, exit_button,
            GA_Text, "Exit",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
        TAG_END),
      TAG_END),
    TAG_END),
  TAG_END);  
  main_gadgets[19] = 0;
}

void main_progress_window( void )
{
  struct Gadget	*main_gadgets[ 8 ];
  Object *window_object = NULL;
  struct HintInfo hintInfo[] =
  {
    {status_container,-1,"",0},
    {status_list_container,-1,"",0},
    {progress_listbrowser,-1,"",0},
    {status_sub_text,-1,"",0},
    {slow_progress_text,-1,"",0},
    {status_buttons_layout,-1,"",0},
    {progress_cancel_button,-1,"Press this to cancel the current iTidy run.  Note: Any changes made to the system will not be undone.",0},
    {-1,-1,NULL,0}
  };
  struct List *labels56;
  UBYTE *labels56_str[] = { NULL };
  labels56 = BrowserNodesA( labels56_str, 1 );

  window_object = NewObject( WINDOW_GetClass(), NULL, 
    WA_Title, "Status",
    WA_Left, 5,
    WA_Top, 20,
    WA_Width, 150,
    WA_Height, 80,
    WA_MinWidth, 150,
    WA_MinHeight, 80,
    WA_MaxWidth, 8192,
    WA_MaxHeight, 8192,
    WINDOW_HintInfo, hintInfo,
    WINDOW_GadgetHelp, TRUE,
    WINDOW_AppPort, gAppPort,
    WA_CloseGadget, TRUE,
    WA_DepthGadget, TRUE,
    WA_SizeGadget, TRUE,
    WA_DragBar, TRUE,
    WA_Activate, TRUE,
    WINDOW_IconTitle, "MyApp",
    WA_NoCareRefresh, TRUE,
    WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_NEWSIZE,
    WINDOW_ParentGroup, NewObject( LAYOUT_GetClass(), NULL,
    LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
    LAYOUT_SpaceOuter, TRUE,
    LAYOUT_DeferLayout, TRUE,
      LAYOUT_AddChild, main_gadgets[status_container] = NewObject( LAYOUT_GetClass(), NULL, 
        GA_ID, status_container,
        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
        LAYOUT_LeftSpacing, 2,
        LAYOUT_RightSpacing, 2,
        LAYOUT_TopSpacing, 2,
        LAYOUT_BottomSpacing, 2,
        LAYOUT_AddChild, main_gadgets[status_list_container] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, status_list_container,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_AddChild, main_gadgets[progress_listbrowser] = NewObject( LISTBROWSER_GetClass(), NULL, 
            GA_ID, progress_listbrowser,
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            LISTBROWSER_Position, 0,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 90,
        LAYOUT_AddChild, main_gadgets[status_sub_text] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, status_sub_text,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_AddChild, main_gadgets[slow_progress_text] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, slow_progress_text,
            GA_Text, "Starting, one moment please...",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_Transparent, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
            BUTTON_BevelStyle, BVS_NONE,
            BUTTON_Justification, BCJ_LEFT,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 5,
        LAYOUT_AddChild, main_gadgets[status_buttons_layout] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, status_buttons_layout,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_AddChild, main_gadgets[progress_cancel_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, progress_cancel_button,
            GA_Text, "Cancel",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          CHILD_MinHeight, 16,
          CHILD_MaxHeight, 28,
        TAG_END),
        CHILD_WeightedHeight, 5,
      TAG_END),
    TAG_END),
  TAG_END);  
  main_gadgets[7] = 0;
}

void advanced_settings( void )
{
  struct Gadget	*main_gadgets[ 31 ];
  Object *window_object = NULL;
  struct HintInfo hintInfo[] =
  {
    {vert_61,-1,"",0},
    {advanced_tab,-1,"",0},
    {advanced_tab_layout,-1,"",0},
    {advanced_layout_aspect,-1,"Sets the target width-to-height shape for drawer windows.",0},
    {advanced_layout_full,-1,"Sets the target width-to-height shape for drawer windows.",0},
    {advanced_layout_align_vertically,-1,"Sets how icons are aligned vertically when a row contains icons of different heights.",0},
    {advanced_tab_density,-1,"",0},
    {advanced_iconspacing_x,-1,"Sets the horizontal gap between icons (in pixels).",0},
    {advanced_iconspacing_y,-1,"Sets the vertical gap between icons (in pixels).",0},
    {space_251,-1,"",0},
    {advanced_tab_limits,-1,"",0},
    {advanced_icons_per_row,-1,"Minimum columns. Prevents drawers becoming one long vertical list.",0},
    {advanced_icons_per_row_autolayout,-1,"When enabled (default), iTidy automatically chooses the maximum columns based on the window width.",0},
    {advanced_icons_per_row_max,-1,"Maximum columns (used only when Auto-calc max icons is disabled).",0},
    {advanced_layout_width,-1,"Limits how wide drawer windows may become (percentage of screen width).",0},
    {advanced_tab_columns_and_groups,-1,"",0},
    {advanced_layout_column_layout,-1,"When enabled, iTidy uses a column-based layout rather than free-flow positioning.",0},
    {advanced_layout_gap_between_groups,-1,"Controls spacing between icon groups when using the 'Grouped by Type' order mode.",0},
    {space_258,-1,"",0},
    {advanced_tab_filters_and_misc,-1,"",0},
    {advanced_layout_skip_hidden,-1,"When enabled (default), iTidy skips folders without .info files during recursive processing.",0},
    {advanced_layout_strip_newicon_borders,-1,"Strips NewIcons borders during processing (requires icon.library v44+). This permanently modifies those icons.",0},
    {advanced_layout_reverse_sort,-1,"Reverses the current sort direction (Z->A, newest-first, or largest-first depending on sort mode).",0},
    {advanced_layout_opitimze_columns,-1,"When enabled (default), each column is sized to its widest icon instead of forcing all columns to the same width.",0},
    {advanced_layout_main_buttons,-1,"",0},
    {advanced_buttons_col1,-1,"",0},
    {advanced_buttons_col2,-1,"",0},
    {advanced_defaults_button,-1,"Resets these settings to defaults.",0},
    {advanced_cancel_button,-1,"Discards changes and returns to the main window.",0},
    {advanced_ok_button,-1,"Accepts changes and closes this window. Use the main window's "Save" menu item to write settings to disk.",0},
    {-1,-1,NULL,0}
  };
  struct List *labels217;
  UBYTE *labels217_str[] = { "Tall (0.75)", "Square (1.0)", "Compact (1.3)", "Classic (1)", "Wide (2.0)",  NULL };
  struct List *labels218;
  UBYTE *labels218_str[] = { "Expand horizontally", "Expand vertically", "Expand both",  NULL };
  struct List *labels219;
  UBYTE *labels219_str[] = { "Top", "Middle", "Bottom",  NULL };
  struct List *labels250;
  UBYTE *labels250_str[] = { "Auto", "30%", "50%", "70%", "90%", "100%",  NULL };
  struct List *labels242;
  UBYTE *labels242_str[] = { "Small", "Medium", "Large",  NULL };
  struct List *labels210;
  UBYTE *labels210_str[] = { "Layout", "Density", "Limits", "Columns & groups", "Filters & misc",  NULL };
  labels217 = ChooserLabelsA( labels217_str );
  labels218 = ChooserLabelsA( labels218_str );
  labels219 = ChooserLabelsA( labels219_str );
  labels250 = ChooserLabelsA( labels250_str );
  labels242 = ChooserLabelsA( labels242_str );
  labels210 = ClickTabsA( labels210_str );

  window_object = NewObject( WINDOW_GetClass(), NULL, 
    WA_Title, "iTidy - Advanced settings",
    WA_Left, 5,
    WA_Top, 20,
    WA_Width, 150,
    WA_Height, 80,
    WA_MinWidth, 150,
    WA_MinHeight, 80,
    WA_MaxWidth, 8192,
    WA_MaxHeight, 8192,
    WINDOW_HintInfo, hintInfo,
    WINDOW_GadgetHelp, TRUE,
    WINDOW_AppPort, gAppPort,
    WA_CloseGadget, TRUE,
    WA_DepthGadget, TRUE,
    WA_SizeGadget, TRUE,
    WA_DragBar, TRUE,
    WA_Activate, TRUE,
    WINDOW_IconTitle, "MyApp",
    WA_NoCareRefresh, TRUE,
    WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_NEWSIZE,
    WINDOW_ParentGroup, NewObject( LAYOUT_GetClass(), NULL,
    LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
    LAYOUT_SpaceOuter, TRUE,
    LAYOUT_DeferLayout, TRUE,
      LAYOUT_AddChild, main_gadgets[vert_61] = NewObject( LAYOUT_GetClass(), NULL, 
        GA_ID, vert_61,
        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
        LAYOUT_AddChild, main_gadgets[advanced_tab] = NewObject( CLICKTAB_GetClass(), NULL, 
          GA_ID, advanced_tab,
          GA_RelVerify, TRUE,
          GA_TabCycle, TRUE,
          GA_Left, 0,
          GA_Top, 0,
          GA_Height, 0,
          CLICKTAB_Labels, labels210,
          CLICKTAB_PageGroup, PageObject,
            LAYOUT_DeferLayout, TRUE,
            PAGE_Add, main_gadgets[advanced_tab_layout] = NewObject( LAYOUT_GetClass(), NULL, 
              GA_ID, advanced_tab_layout,
              LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_LeftSpacing, 2,
              LAYOUT_RightSpacing, 2,
              LAYOUT_TopSpacing, 2,
              LAYOUT_BottomSpacing, 2,
              LAYOUT_AddChild, main_gadgets[advanced_layout_aspect] = NewObject( CHOOSER_GetClass(), NULL, 
                GA_ID, advanced_layout_aspect,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHOOSER_PopUp, TRUE,
                CHOOSER_Selected, 0,
                CHOOSER_AutoFit, TRUE,
                CHOOSER_Labels, labels217,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Layout aspect",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[advanced_layout_full] = NewObject( CHOOSER_GetClass(), NULL, 
                GA_ID, advanced_layout_full,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHOOSER_PopUp, TRUE,
                CHOOSER_Selected, 0,
                CHOOSER_AutoFit, TRUE,
                CHOOSER_Labels, labels218,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "When full",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[advanced_layout_align_vertically] = NewObject( CHOOSER_GetClass(), NULL, 
                GA_ID, advanced_layout_align_vertically,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHOOSER_PopUp, TRUE,
                CHOOSER_Selected, 0,
                CHOOSER_Labels, labels219,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Align vertically",
              TAG_END),
            TAG_END),
            PAGE_Add, main_gadgets[advanced_tab_density] = NewObject( LAYOUT_GetClass(), NULL, 
              GA_ID, advanced_tab_density,
              LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_LeftSpacing, 2,
              LAYOUT_RightSpacing, 2,
              LAYOUT_TopSpacing, 2,
              LAYOUT_BottomSpacing, 2,
              LAYOUT_AddChild, main_gadgets[advanced_iconspacing_x] = NewObject( INTEGER_GetClass(), NULL, 
                GA_ID, advanced_iconspacing_x,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                INTEGER_Minimum, 0,
                INTEGER_Maximum, 20,
                INTEGER_MinVisible, 10,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Horizontal spacing",
              TAG_END),
              CHILD_NominalSize, TRUE,
              LAYOUT_AddChild, main_gadgets[advanced_iconspacing_y] = NewObject( INTEGER_GetClass(), NULL, 
                GA_ID, advanced_iconspacing_y,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                INTEGER_MaxChars, 2,
                INTEGER_Minimum, 0,
                INTEGER_Maximum, 20,
                INTEGER_MinVisible, 2,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Vertical spacing",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[space_251] = NewObject( SPACE_GetClass(), NULL, 
                GA_ID, space_251,
              TAG_END),
            TAG_END),
            PAGE_Add, main_gadgets[advanced_tab_limits] = NewObject( LAYOUT_GetClass(), NULL, 
              GA_ID, advanced_tab_limits,
              LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_LeftSpacing, 2,
              LAYOUT_RightSpacing, 2,
              LAYOUT_TopSpacing, 2,
              LAYOUT_BottomSpacing, 2,
              LAYOUT_AddChild, main_gadgets[advanced_icons_per_row] = NewObject( INTEGER_GetClass(), NULL, 
                GA_ID, advanced_icons_per_row,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                INTEGER_Minimum, 0,
                INTEGER_Maximum, 30,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Icons per row: Min",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[advanced_icons_per_row_autolayout] = NewObject( CHECKBOX_GetClass(), NULL, 
                GA_ID, advanced_icons_per_row_autolayout,
                GA_Text, "",
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                GA_Selected, TRUE,
                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Auto-calc max icons",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[advanced_icons_per_row_max] = NewObject( INTEGER_GetClass(), NULL, 
                GA_ID, advanced_icons_per_row_max,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                GA_Disabled, TRUE,
                INTEGER_Minimum, 2,
                INTEGER_Maximum, 40,
                INTEGER_Arrows, FALSE,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Max",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[advanced_layout_width] = NewObject( CHOOSER_GetClass(), NULL, 
                GA_ID, advanced_layout_width,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHOOSER_PopUp, TRUE,
                CHOOSER_Selected, 0,
                CHOOSER_Labels, labels250,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Max window width",
              TAG_END),
            TAG_END),
            PAGE_Add, main_gadgets[advanced_tab_columns_and_groups] = NewObject( LAYOUT_GetClass(), NULL, 
              GA_ID, advanced_tab_columns_and_groups,
              LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_LeftSpacing, 2,
              LAYOUT_RightSpacing, 2,
              LAYOUT_TopSpacing, 2,
              LAYOUT_BottomSpacing, 2,
              LAYOUT_AddChild, main_gadgets[advanced_layout_column_layout] = NewObject( CHECKBOX_GetClass(), NULL, 
                GA_ID, advanced_layout_column_layout,
                GA_Text, "",
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Column layout",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[advanced_layout_gap_between_groups] = NewObject( CHOOSER_GetClass(), NULL, 
                GA_ID, advanced_layout_gap_between_groups,
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHOOSER_PopUp, TRUE,
                CHOOSER_Selected, 0,
                CHOOSER_Labels, labels242,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Gap between groups",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[space_258] = NewObject( SPACE_GetClass(), NULL, 
                GA_ID, space_258,
              TAG_END),
            TAG_END),
            PAGE_Add, main_gadgets[advanced_tab_filters_and_misc] = NewObject( LAYOUT_GetClass(), NULL, 
              GA_ID, advanced_tab_filters_and_misc,
              LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_LeftSpacing, 2,
              LAYOUT_RightSpacing, 2,
              LAYOUT_TopSpacing, 2,
              LAYOUT_BottomSpacing, 2,
              LAYOUT_AddChild, main_gadgets[advanced_layout_skip_hidden] = NewObject( CHECKBOX_GetClass(), NULL, 
                GA_ID, advanced_layout_skip_hidden,
                GA_Text, "",
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Skip hidden folders",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[advanced_layout_strip_newicon_borders] = NewObject( CHECKBOX_GetClass(), NULL, 
                GA_ID, advanced_layout_strip_newicon_borders,
                GA_Text, "",
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Strip NewIcons borders (permanent)",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[advanced_layout_reverse_sort] = NewObject( CHECKBOX_GetClass(), NULL, 
                GA_ID, advanced_layout_reverse_sort,
                GA_Text, "",
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Reverse sort order",
              TAG_END),
              LAYOUT_AddChild, main_gadgets[advanced_layout_opitimze_columns] = NewObject( CHECKBOX_GetClass(), NULL, 
                GA_ID, advanced_layout_opitimze_columns,
                GA_Text, "",
                GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
              TAG_END),
              CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
                LABEL_Text, "Auto-fit columns",
              TAG_END),
            TAG_END),
          PageEnd,
        TAG_END),
        CHILD_WeightedHeight, 95,
        LAYOUT_AddChild, main_gadgets[advanced_layout_main_buttons] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, advanced_layout_main_buttons,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_LeftSpacing, 2,
          LAYOUT_RightSpacing, 2,
          LAYOUT_TopSpacing, 4,
          LAYOUT_BottomSpacing, 2,
          LAYOUT_AddChild, main_gadgets[advanced_buttons_col1] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, advanced_buttons_col1,
            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          TAG_END),
          CHILD_WeightedWidth, 50,
          LAYOUT_AddChild, main_gadgets[advanced_buttons_col2] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, advanced_buttons_col2,
            LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
            LAYOUT_AddChild, main_gadgets[advanced_defaults_button] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, advanced_defaults_button,
              GA_Text, "Defaults",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
            TAG_END),
            LAYOUT_AddChild, main_gadgets[advanced_cancel_button] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, advanced_cancel_button,
              GA_Text, "Cancel",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
            TAG_END),
            LAYOUT_AddChild, main_gadgets[advanced_ok_button] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, advanced_ok_button,
              GA_Text, "OK",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
            TAG_END),
          TAG_END),
          CHILD_WeightedWidth, 50,
        TAG_END),
        CHILD_WeightedHeight, 5,
      TAG_END),
    TAG_END),
  TAG_END);  
  main_gadgets[30] = 0;
}

void restore_backups( void )
{
  struct Gadget	*main_gadgets[ 11 ];
  Object *window_object = NULL;
  struct HintInfo hintInfo[] =
  {
    {vert_105,-1,"",0},
    {backup_list_layout,-1,"",0},
    {backup_list,-1,"",0},
    {backup_details_layout,-1,"",0},
    {details_browser,-1,"",0},
    {backup_buttons_row1_layout,-1,"",0},
    {backup_delete_run,-1,"",0},
    {backup_restore_run,-1,"",0},
    {backup_view_folders,-1,"",0},
    {button_cancel,-1,"",0},
    {-1,-1,NULL,0}
  };
  struct List *labels107;
  UBYTE *labels107_str[] = { NULL };
  struct List *labels117;
  UBYTE *labels117_str[] = { NULL };
  struct ColumnInfo ListBrowser107_ci[] =
  {
    { 1, "", 0 },
    { -1, (STRPTR)~0, -1 }
  };

  labels107 = BrowserNodesA( labels107_str, 1 );
  labels117 = BrowserNodesA( labels117_str, 1 );

  window_object = NewObject( WINDOW_GetClass(), NULL, 
    WA_Title, "iTidy - Restore backups",
    WA_Left, 5,
    WA_Top, 20,
    WA_Width, 150,
    WA_Height, 80,
    WA_MinWidth, 150,
    WA_MinHeight, 80,
    WA_MaxWidth, 8192,
    WA_MaxHeight, 8192,
    WINDOW_HintInfo, hintInfo,
    WINDOW_GadgetHelp, TRUE,
    WINDOW_AppPort, gAppPort,
    WA_CloseGadget, TRUE,
    WA_DepthGadget, TRUE,
    WA_SizeGadget, TRUE,
    WA_DragBar, TRUE,
    WA_Activate, TRUE,
    WINDOW_IconTitle, "MyApp",
    WA_NoCareRefresh, TRUE,
    WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_NEWSIZE,
    WINDOW_ParentGroup, NewObject( LAYOUT_GetClass(), NULL,
    LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
    LAYOUT_SpaceOuter, TRUE,
    LAYOUT_DeferLayout, TRUE,
      LAYOUT_AddChild, main_gadgets[vert_105] = NewObject( LAYOUT_GetClass(), NULL, 
        GA_ID, vert_105,
        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
        LAYOUT_AddChild, main_gadgets[backup_list_layout] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, backup_list_layout,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_LeftSpacing, 2,
          LAYOUT_RightSpacing, 2,
          LAYOUT_TopSpacing, 2,
          LAYOUT_BottomSpacing, 2,
          LAYOUT_AddChild, main_gadgets[backup_list] = NewObject( LISTBROWSER_GetClass(), NULL, 
            GA_ID, backup_list,
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            LISTBROWSER_Position, 0,
            LISTBROWSER_ColumnInfo, &ListBrowser107_ci,
            LISTBROWSER_ColumnTitles, TRUE,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 45,
        LAYOUT_AddChild, main_gadgets[backup_details_layout] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, backup_details_layout,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_LeftSpacing, 2,
          LAYOUT_RightSpacing, 2,
          LAYOUT_TopSpacing, 2,
          LAYOUT_BottomSpacing, 2,
          LAYOUT_AddChild, main_gadgets[details_browser] = NewObject( LISTBROWSER_GetClass(), NULL, 
            GA_ID, details_browser,
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            LISTBROWSER_Position, 0,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 45,
        LAYOUT_AddChild, main_gadgets[backup_buttons_row1_layout] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, backup_buttons_row1_layout,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_AddChild, main_gadgets[backup_delete_run] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, backup_delete_run,
            GA_Text, "Delete run",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[backup_restore_run] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, backup_restore_run,
            GA_Text, "Restore run",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[backup_view_folders] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, backup_view_folders,
            GA_Text, "View folders",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[button_cancel] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, button_cancel,
            GA_Text, "Cancel",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 10,
      TAG_END),
    TAG_END),
  TAG_END);  
  main_gadgets[10] = 0;
}

void restore_folders_view( void )
{
  struct Gadget	*main_gadgets[ 4 ];
  Object *window_object = NULL;
  struct HintInfo hintInfo[] =
  {
    {vert_120,-1,"",0},
    {folder_browser,-1,"",0},
    {close_button,-1,"",0},
    {-1,-1,NULL,0}
  };
  struct List *labels121;
  UBYTE *labels121_str[] = { NULL };
  labels121 = BrowserNodesA( labels121_str, 1 );

  window_object = NewObject( WINDOW_GetClass(), NULL, 
    WA_Title, "Folder View",
    WA_Left, 5,
    WA_Top, 20,
    WA_Width, 150,
    WA_Height, 80,
    WA_MinWidth, 150,
    WA_MinHeight, 80,
    WA_MaxWidth, 8192,
    WA_MaxHeight, 8192,
    WINDOW_HintInfo, hintInfo,
    WINDOW_GadgetHelp, TRUE,
    WINDOW_AppPort, gAppPort,
    WA_CloseGadget, TRUE,
    WA_DepthGadget, TRUE,
    WA_SizeGadget, TRUE,
    WA_DragBar, TRUE,
    WA_Activate, TRUE,
    WINDOW_IconTitle, "MyApp",
    WA_NoCareRefresh, TRUE,
    WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_NEWSIZE,
    WINDOW_ParentGroup, NewObject( LAYOUT_GetClass(), NULL,
    LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
    LAYOUT_SpaceOuter, TRUE,
    LAYOUT_DeferLayout, TRUE,
      LAYOUT_AddChild, main_gadgets[vert_120] = NewObject( LAYOUT_GetClass(), NULL, 
        GA_ID, vert_120,
        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
        LAYOUT_AddChild, main_gadgets[folder_browser] = NewObject( LISTBROWSER_GetClass(), NULL, 
          GA_ID, folder_browser,
          GA_RelVerify, TRUE,
          GA_TabCycle, TRUE,
          LISTBROWSER_Position, 0,
        TAG_END),
        CHILD_WeightedHeight, 99,
        LAYOUT_AddChild, main_gadgets[close_button] = NewObject( BUTTON_GetClass(), NULL, 
          GA_ID, close_button,
          GA_Text, "Close",
          GA_RelVerify, TRUE,
          GA_TabCycle, TRUE,
          BUTTON_TextPen, 1,
          BUTTON_BackgroundPen, 0,
          BUTTON_FillTextPen, 1,
          BUTTON_FillPen, 3,
        TAG_END),
        CHILD_WeightedHeight, 1,
        CHILD_ScaleHeight, 1,
      TAG_END),
    TAG_END),
  TAG_END);  
  main_gadgets[3] = 0;
}

void recursive_progress_window( void )
{
  struct Gadget	*main_gadgets[ 6 ];
  Object *window_object = NULL;
  struct HintInfo hintInfo[] =
  {
    {vert_125,-1,"",0},
    {main_progress_bar,-1,"",0},
    {main_progress_label,-1,"",0},
    {sub_progress_bar,-1,"",0},
    {sub_process_label,-1,"",0},
    {-1,-1,NULL,0}
  };

  window_object = NewObject( WINDOW_GetClass(), NULL, 
    WA_Title, "Progress...",
    WA_Left, 5,
    WA_Top, 20,
    WA_Width, 150,
    WA_Height, 80,
    WA_MinWidth, 250,
    WA_MinHeight, 80,
    WA_MaxWidth, 8192,
    WA_MaxHeight, 8192,
    WINDOW_HintInfo, hintInfo,
    WINDOW_GadgetHelp, TRUE,
    WINDOW_AppPort, gAppPort,
    WA_DepthGadget, TRUE,
    WA_SizeGadget, TRUE,
    WA_DragBar, TRUE,
    WA_Activate, TRUE,
    WINDOW_IconTitle, "MyApp",
    WA_NoCareRefresh, TRUE,
    WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW,
    WINDOW_ParentGroup, NewObject( LAYOUT_GetClass(), NULL,
    LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
    LAYOUT_SpaceOuter, TRUE,
    LAYOUT_DeferLayout, TRUE,
      LAYOUT_AddChild, main_gadgets[vert_125] = NewObject( LAYOUT_GetClass(), NULL, 
        GA_ID, vert_125,
        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
        LAYOUT_LeftSpacing, 2,
        LAYOUT_RightSpacing, 2,
        LAYOUT_TopSpacing, 2,
        LAYOUT_BottomSpacing, 2,
        LAYOUT_AddChild, main_gadgets[main_progress_bar] = NewObject( FUELGAUGE_GetClass(), NULL, 
          GA_ID, main_progress_bar,
          GA_RelVerify, TRUE,
          GA_Text, 1079073956,
          FUELGAUGE_Min, 0,
          FUELGAUGE_Max, 0,
          FUELGAUGE_Level, 0,
          FUELGAUGE_Ticks, 0,
          FUELGAUGE_Percent, FALSE,
          FUELGAUGE_FillPen, FILLPEN,
        TAG_END),
        LAYOUT_AddImage, main_gadgets[main_progress_label] = NewObject( LABEL_GetClass(), NULL, 
          GA_ID, main_progress_label,
          LABEL_DrawInfo, gDrawInfo,
          LABEL_Text, "Starting, one moment please...",
        TAG_END),
        LAYOUT_AddChild, main_gadgets[sub_progress_bar] = NewObject( FUELGAUGE_GetClass(), NULL, 
          GA_ID, sub_progress_bar,
          GA_RelVerify, TRUE,
          GA_Text, 1079074668,
          FUELGAUGE_Min, 0,
          FUELGAUGE_Max, 0,
          FUELGAUGE_Level, 0,
          FUELGAUGE_Ticks, 0,
          FUELGAUGE_Percent, FALSE,
          FUELGAUGE_FillPen, FILLPEN,
        TAG_END),
        LAYOUT_AddImage, main_gadgets[sub_process_label] = NewObject( LABEL_GetClass(), NULL, 
          GA_ID, sub_process_label,
          LABEL_DrawInfo, gDrawInfo,
          LABEL_Text, "Processing",
        TAG_END),
      TAG_END),
    TAG_END),
  TAG_END);  
  main_gadgets[5] = 0;
}

void default_tool_analysis( void )
{
  struct NewMenu menuData[] =
  {
    { NM_TITLE, "Project", 0, 0, 0, NULL },
    { NM_ITEM, "New", "N", 0, 126, NULL },
    { NM_ITEM, "Open", "O", 0, 125, NULL },
    { NM_ITEM, NM_BARLABEL, 0, 0, 123, NULL },
    { NM_ITEM, "Save", "S", 0, 119, NULL },
    { NM_ITEM, "Save as...", "A", 0, 111, NULL },
    { NM_ITEM, NM_BARLABEL, 0, 0, 95, NULL },
    { NM_ITEM, "Close", 0, 0, 63, NULL },
    { NM_TITLE, "File", 0, 0, 0, NULL },
    { NM_ITEM, "Export list of tools", "T", 0, 2, NULL },
    { NM_ITEM, "Export list of files and tools", "F", 0, 1, NULL },
    { NM_TITLE, "View", 0, 0, 0, NULL },
    { NM_ITEM, "System PATH", "P", 0, 0, NULL },
    { NM_END, NULL, 0, 0, 0, (APTR)0 }
  };

  struct Menu	*menu_strip = NULL;
  struct Gadget	*main_gadgets[ 17 ];
  Object *window_object = NULL;
  struct HintInfo hintInfo[] =
  {
    {vert_134,-1,"",0},
    {tool_folder_location,-1,"",0},
    {tools_folder_name,-1,"",0},
    {scan_button,-1,"",0},
    {tool_details_layout,-1,"",0},
    {tools_filter,-1,"",0},
    {tool_status_list,-1,"",0},
    {tool_status_layout,-1,"",0},
    {tool_status_listview,-1,"",0},
    {tool_status_buttons,-1,"",0},
    {tool_status_layout_col1,-1,"",0},
    {replace_tool_batch,-1,"",0},
    {resore_default_tools_backup,-1,"",0},
    {tool_status_layout_col2,-1,"",0},
    {replace_tool_single,-1,"",0},
    {tools_close_button,-1,"",0},
    {-1,-1,NULL,0}
  };
  struct List *labels141;
  UBYTE *labels141_str[] = { "Show all", "show valid only", "Show missing only",  NULL };
  struct List *labels142;
  UBYTE *labels142_str[] = { NULL };
  struct List *labels143;
  UBYTE *labels143_str[] = { NULL };
  struct ColumnInfo ListBrowser142_ci[] =
  {
    { 1, "", 0 },
    { -1, (STRPTR)~0, -1 }
  };

  menu_strip = CreateMenusA( menuData, TAG_END );
  LayoutMenus( menu_strip, gVisinfo,
    GTMN_NewLookMenus, TRUE,
    TAG_DONE );

  labels141 = ChooserLabelsA( labels141_str );
  labels142 = BrowserNodesA( labels142_str, 1 );
  labels143 = ListViewLabelsA( labels143_str );

  window_object = NewObject( WINDOW_GetClass(), NULL, 
    WA_Title, "iTidy - default tool analysis",
    WA_Left, 5,
    WA_Top, 20,
    WA_Width, 150,
    WA_Height, 80,
    WA_MinWidth, 150,
    WA_MinHeight, 80,
    WA_MaxWidth, 8192,
    WA_MaxHeight, 8192,
    WINDOW_HintInfo, hintInfo,
    WINDOW_GadgetHelp, TRUE,
    WINDOW_AppPort, gAppPort,
    WA_CloseGadget, TRUE,
    WA_DepthGadget, TRUE,
    WA_SizeGadget, TRUE,
    WA_DragBar, TRUE,
    WA_Activate, TRUE,
    WINDOW_IconTitle, "MyApp",
    WA_NoCareRefresh, TRUE,
    WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_NEWSIZE,
    WINDOW_ParentGroup, NewObject( LAYOUT_GetClass(), NULL,
    LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
    LAYOUT_SpaceOuter, TRUE,
    LAYOUT_DeferLayout, TRUE,
      LAYOUT_AddChild, main_gadgets[vert_134] = NewObject( LAYOUT_GetClass(), NULL, 
        GA_ID, vert_134,
        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
        LAYOUT_LeftSpacing, 2,
        LAYOUT_RightSpacing, 2,
        LAYOUT_TopSpacing, 2,
        LAYOUT_BottomSpacing, 2,
        LAYOUT_AddChild, main_gadgets[tool_folder_location] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, tool_folder_location,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_AddChild, main_gadgets[tools_folder_name] = NewObject( GETFILE_GetClass(), NULL, 
            GA_ID, tools_folder_name,
            GA_RelVerify, TRUE,
            GETFILE_TitleText, "Select a file",
            GETFILE_Drawer, "folder_name_string",
            GETFILE_FullFile, "Sys:",
            GETFILE_FilterDrawers, TRUE,
            GETFILE_ReadOnly, TRUE,
          TAG_END),
          CHILD_Label, NewObject( LABEL_GetClass(), NULL, 
            LABEL_Text, "Folder",
          TAG_END),
          CHILD_WeightedWidth, 70,
          LAYOUT_AddChild, main_gadgets[scan_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, scan_button,
            GA_Text, "Scan",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          CHILD_WeightedWidth, 30,
        TAG_END),
        CHILD_WeightedHeight, 5,
        LAYOUT_AddChild, main_gadgets[tool_details_layout] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, tool_details_layout,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_AddChild, main_gadgets[tools_filter] = NewObject( CHOOSER_GetClass(), NULL, 
            GA_ID, tools_filter,
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            CHOOSER_PopUp, TRUE,
            CHOOSER_Selected, 0,
            CHOOSER_Labels, labels141,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[tool_status_list] = NewObject( LISTBROWSER_GetClass(), NULL, 
            GA_ID, tool_status_list,
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            LISTBROWSER_Position, 0,
            LISTBROWSER_ColumnInfo, &ListBrowser142_ci,
            LISTBROWSER_ColumnTitles, TRUE,
            LISTBROWSER_AutoFit, TRUE,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 50,
        LAYOUT_AddChild, main_gadgets[tool_status_layout] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, tool_status_layout,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_TopSpacing, 2,
          LAYOUT_ShrinkWrap, TRUE,
          LAYOUT_AddChild, main_gadgets[tool_status_listview] = NewObject( LISTVIEW_GetClass(), NULL, 
            GA_ID, tool_status_listview,
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            LISTVIEW_Labels, labels143,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 30,
        LAYOUT_AddChild, main_gadgets[tool_status_buttons] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, tool_status_buttons,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_AddChild, main_gadgets[tool_status_layout_col1] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, tool_status_layout_col1,
            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
            LAYOUT_AddChild, main_gadgets[replace_tool_batch] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, replace_tool_batch,
              GA_Text, "Replace tool (batch)",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
            TAG_END),
            LAYOUT_AddChild, main_gadgets[resore_default_tools_backup] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, resore_default_tools_backup,
              GA_Text, "Restore default tools backup",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
            TAG_END),
          TAG_END),
          LAYOUT_AddChild, main_gadgets[tool_status_layout_col2] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, tool_status_layout_col2,
            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
            LAYOUT_HorizAlignment, LALIGN_RIGHT,
            LAYOUT_AddChild, main_gadgets[replace_tool_single] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, replace_tool_single,
              GA_Text, "Replace tool (single)",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
            TAG_END),
            LAYOUT_AddChild, main_gadgets[tools_close_button] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, tools_close_button,
              GA_Text, "Close",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
            TAG_END),
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 10,
      TAG_END),
    TAG_END),
  TAG_END);  
  main_gadgets[16] = 0;
}

void default_tool_update( void )
{
  struct Gadget	*main_gadgets[ 17 ];
  Object *window_object = NULL;
  struct HintInfo hintInfo[] =
  {
    {vert_154,-1,"",0},
    {current_tool_layout_horizontal,-1,"",0},
    {current_tool_layout_col1,-1,"",0},
    {label_current_tool,-1,"",0},
    {mode_text,-1,"",0},
    {change_to_label2,-1,"",0},
    {current_tool_layout_col2,-1,"",0},
    {current_tool_text,-1,"",0},
    {current_mode_text,-1,"",0},
    {default_tool_new_tool,-1,"",0},
    {update_progress_listview,-1,"",0},
    {update_progress_label,-1,"",0},
    {listview_update_progress,-1,"",0},
    {default_tool_buttons,-1,"",0},
    {default_tool_update_button,-1,"",0},
    {update_tool_close,-1,"",0},
    {-1,-1,NULL,0}
  };
  struct List *labels179;
  UBYTE *labels179_str[] = { NULL };
  struct ColumnInfo ListBrowser179_ci[] =
  {
    { 1, "", 0 },
    { -1, (STRPTR)~0, -1 }
  };

  labels179 = BrowserNodesA( labels179_str, 1 );

  window_object = NewObject( WINDOW_GetClass(), NULL, 
    WA_Title, "iTidy - Replace default tool",
    WA_Left, 5,
    WA_Top, 20,
    WA_Width, 150,
    WA_Height, 80,
    WA_MinWidth, 150,
    WA_MinHeight, 80,
    WA_MaxWidth, 8192,
    WA_MaxHeight, 8192,
    WINDOW_HintInfo, hintInfo,
    WINDOW_GadgetHelp, TRUE,
    WINDOW_AppPort, gAppPort,
    WA_CloseGadget, TRUE,
    WA_DepthGadget, TRUE,
    WA_SizeGadget, TRUE,
    WA_DragBar, TRUE,
    WA_Activate, TRUE,
    WINDOW_IconTitle, "MyApp",
    WA_NoCareRefresh, TRUE,
    WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_NEWSIZE,
    WINDOW_ParentGroup, NewObject( LAYOUT_GetClass(), NULL,
    LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
    LAYOUT_SpaceOuter, TRUE,
    LAYOUT_DeferLayout, TRUE,
      LAYOUT_AddChild, main_gadgets[vert_154] = NewObject( LAYOUT_GetClass(), NULL, 
        GA_ID, vert_154,
        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
        LAYOUT_LeftSpacing, 2,
        LAYOUT_RightSpacing, 2,
        LAYOUT_TopSpacing, 2,
        LAYOUT_AddChild, main_gadgets[current_tool_layout_horizontal] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, current_tool_layout_horizontal,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_BevelStyle, BVS_STANDARD,
          LAYOUT_LeftSpacing, 2,
          LAYOUT_RightSpacing, 2,
          LAYOUT_TopSpacing, 2,
          LAYOUT_BottomSpacing, 4,
          LAYOUT_AddChild, main_gadgets[current_tool_layout_col1] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, current_tool_layout_col1,
            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
            LAYOUT_HorizAlignment, LALIGN_RIGHT,
            LAYOUT_AddChild, main_gadgets[label_current_tool] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, label_current_tool,
              GA_Text, "Current tool:",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_Transparent, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
              BUTTON_BevelStyle, BVS_NONE,
              BUTTON_Justification, BCJ_RIGHT,
            TAG_END),
            LAYOUT_AddChild, main_gadgets[mode_text] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, mode_text,
              GA_Text, "Mode:",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_Transparent, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
              BUTTON_BevelStyle, BVS_NONE,
              BUTTON_Justification, BCJ_RIGHT,
            TAG_END),
            LAYOUT_AddChild, main_gadgets[change_to_label2] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, change_to_label2,
              GA_Text, "Change to:",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_Transparent, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
              BUTTON_BevelStyle, BVS_NONE,
              BUTTON_Justification, BCJ_RIGHT,
            TAG_END),
          TAG_END),
          CHILD_WeightedWidth, 20,
          LAYOUT_AddChild, main_gadgets[current_tool_layout_col2] = NewObject( LAYOUT_GetClass(), NULL, 
            GA_ID, current_tool_layout_col2,
            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
            LAYOUT_AddChild, main_gadgets[current_tool_text] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, current_tool_text,
              GA_Text, "current tool text",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_Transparent, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
              BUTTON_BevelStyle, BVS_NONE,
              BUTTON_Justification, BCJ_LEFT,
            TAG_END),
            LAYOUT_AddChild, main_gadgets[current_mode_text] = NewObject( BUTTON_GetClass(), NULL, 
              GA_ID, current_mode_text,
              GA_Text, "curren mode text",
              GA_RelVerify, TRUE,
              GA_TabCycle, TRUE,
              BUTTON_Transparent, TRUE,
              BUTTON_TextPen, 1,
              BUTTON_BackgroundPen, 0,
              BUTTON_FillTextPen, 1,
              BUTTON_FillPen, 3,
              BUTTON_BevelStyle, BVS_NONE,
              BUTTON_Justification, BCJ_LEFT,
            TAG_END),
            LAYOUT_AddChild, main_gadgets[default_tool_new_tool] = NewObject( GETFILE_GetClass(), NULL, 
              GA_ID, default_tool_new_tool,
              GA_RelVerify, TRUE,
              GETFILE_TitleText, "Select a file",
              GETFILE_ReadOnly, TRUE,
            TAG_END),
          TAG_END),
          CHILD_WeightedWidth, 80,
        TAG_END),
        CHILD_WeightedHeight, 5,
        LAYOUT_AddChild, main_gadgets[update_progress_listview] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, update_progress_listview,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_HorizAlignment, LALIGN_CENTER,
          LAYOUT_TopSpacing, 2,
          LAYOUT_BottomSpacing, 2,
          LAYOUT_AddImage, main_gadgets[update_progress_label] = NewObject( LABEL_GetClass(), NULL, 
            GA_ID, update_progress_label,
            LABEL_DrawInfo, gDrawInfo,
            LABEL_Text, "Update progress",
            LABEL_Justification, LJ_CENTER,
          TAG_END),
          CHILD_WeightedHeight, 5,
          LAYOUT_AddChild, main_gadgets[listview_update_progress] = NewObject( LISTBROWSER_GetClass(), NULL, 
            GA_ID, listview_update_progress,
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            LISTBROWSER_Position, 0,
            LISTBROWSER_ColumnInfo, &ListBrowser179_ci,
            LISTBROWSER_ColumnTitles, TRUE,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 80,
        LAYOUT_AddChild, main_gadgets[default_tool_buttons] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, default_tool_buttons,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_BottomSpacing, 2,
          LAYOUT_AddChild, main_gadgets[default_tool_update_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, default_tool_update_button,
            GA_Text, "Update default tool",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[update_tool_close] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, update_tool_close,
            GA_Text, "Close",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 5,
      TAG_END),
    TAG_END),
  TAG_END);  
  main_gadgets[16] = 0;
}

void restore_default_tool( void )
{
  struct Gadget	*main_gadgets[ 12 ];
  Object *window_object = NULL;
  struct HintInfo hintInfo[] =
  {
    {vert_182,-1,"",0},
    {backup_session_layout,-1,"",0},
    {restore_listbrowser_label,-1,"",0},
    {backup_sessions_listbrowser,-1,"",0},
    {tool_changes_sesssion,-1,"",0},
    {tool_changes_label,-1,"",0},
    {tool_changes_listbroswer,-1,"",0},
    {restore_tools_buttons,-1,"",0},
    {restore_tools_restore_button,-1,"",0},
    {restore_tools_delete_button,-1,"",0},
    {restore_tools_close_button,-1,"",0},
    {-1,-1,NULL,0}
  };
  struct List *labels185;
  UBYTE *labels185_str[] = { NULL };
  struct List *labels193;
  UBYTE *labels193_str[] = { NULL };
  struct ColumnInfo ListBrowser185_ci[] =
  {
    { 1, "", 0 },
    { -1, (STRPTR)~0, -1 }
  };

  labels185 = BrowserNodesA( labels185_str, 1 );
  labels193 = BrowserNodesA( labels193_str, 1 );

  window_object = NewObject( WINDOW_GetClass(), NULL, 
    WA_Title, "iTidy - restore default tool",
    WA_Left, 5,
    WA_Top, 20,
    WA_Width, 150,
    WA_Height, 80,
    WA_MinWidth, 150,
    WA_MinHeight, 80,
    WA_MaxWidth, 8192,
    WA_MaxHeight, 8192,
    WINDOW_HintInfo, hintInfo,
    WINDOW_GadgetHelp, TRUE,
    WINDOW_AppPort, gAppPort,
    WA_CloseGadget, TRUE,
    WA_DepthGadget, TRUE,
    WA_SizeGadget, TRUE,
    WA_DragBar, TRUE,
    WA_Activate, TRUE,
    WINDOW_IconTitle, "MyApp",
    WA_NoCareRefresh, TRUE,
    WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_NEWSIZE,
    WINDOW_ParentGroup, NewObject( LAYOUT_GetClass(), NULL,
    LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
    LAYOUT_SpaceOuter, TRUE,
    LAYOUT_DeferLayout, TRUE,
      LAYOUT_AddChild, main_gadgets[vert_182] = NewObject( LAYOUT_GetClass(), NULL, 
        GA_ID, vert_182,
        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
        LAYOUT_AddChild, main_gadgets[backup_session_layout] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, backup_session_layout,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_HorizAlignment, LALIGN_CENTER,
          LAYOUT_LeftSpacing, 2,
          LAYOUT_RightSpacing, 2,
          LAYOUT_TopSpacing, 2,
          LAYOUT_BottomSpacing, 2,
          LAYOUT_AddImage, main_gadgets[restore_listbrowser_label] = NewObject( LABEL_GetClass(), NULL, 
            GA_ID, restore_listbrowser_label,
            LABEL_DrawInfo, gDrawInfo,
            LABEL_Text, "Backup sessions:",
            LABEL_Justification, LJ_CENTER,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[backup_sessions_listbrowser] = NewObject( LISTBROWSER_GetClass(), NULL, 
            GA_ID, backup_sessions_listbrowser,
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            LISTBROWSER_Position, 0,
            LISTBROWSER_ColumnInfo, &ListBrowser185_ci,
            LISTBROWSER_ColumnTitles, TRUE,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 60,
        LAYOUT_AddChild, main_gadgets[tool_changes_sesssion] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, tool_changes_sesssion,
          LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
          LAYOUT_HorizAlignment, LALIGN_CENTER,
          LAYOUT_LeftSpacing, 2,
          LAYOUT_RightSpacing, 2,
          LAYOUT_BottomSpacing, 2,
          LAYOUT_AddImage, main_gadgets[tool_changes_label] = NewObject( LABEL_GetClass(), NULL, 
            GA_ID, tool_changes_label,
            LABEL_DrawInfo, gDrawInfo,
            LABEL_Text, "Tool changes in session",
          TAG_END),
          LAYOUT_AddChild, main_gadgets[tool_changes_listbroswer] = NewObject( LISTBROWSER_GetClass(), NULL, 
            GA_ID, tool_changes_listbroswer,
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            LISTBROWSER_Position, 0,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 35,
        LAYOUT_AddChild, main_gadgets[restore_tools_buttons] = NewObject( LAYOUT_GetClass(), NULL, 
          GA_ID, restore_tools_buttons,
          LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
          LAYOUT_LeftSpacing, 2,
          LAYOUT_RightSpacing, 2,
          LAYOUT_TopSpacing, 2,
          LAYOUT_BottomSpacing, 2,
          LAYOUT_AddChild, main_gadgets[restore_tools_restore_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, restore_tools_restore_button,
            GA_Text, "Restore",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[restore_tools_delete_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, restore_tools_delete_button,
            GA_Text, "Delete",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
          LAYOUT_AddChild, main_gadgets[restore_tools_close_button] = NewObject( BUTTON_GetClass(), NULL, 
            GA_ID, restore_tools_close_button,
            GA_Text, "Close",
            GA_RelVerify, TRUE,
            GA_TabCycle, TRUE,
            BUTTON_TextPen, 1,
            BUTTON_BackgroundPen, 0,
            BUTTON_FillTextPen, 1,
            BUTTON_FillPen, 3,
          TAG_END),
        TAG_END),
        CHILD_WeightedHeight, 5,
      TAG_END),
    TAG_END),
  TAG_END);  
  main_gadgets[11] = 0;
}

