/*
 * advanced_window_reaction.c - iTidy Advanced Settings Window (ReAction)
 * ReAction-based GUI for Workbench 3.2+
 */

/* Redefine library bases to local unique names BEFORE including proto headers */
/* This prevents collision with WindowBase defined in main_window.o */
/* The system headers declare 'extern struct Library *WindowBase', which the */
/* preprocessor will change to 'extern struct Library *iTidy_WindowBase'. */
#define WindowBase iTidy_WindowBase
#define LayoutBase iTidy_LayoutBase
#define ButtonBase iTidy_ButtonBase
#define CheckBoxBase iTidy_CheckBoxBase
#define ChooserBase iTidy_ChooserBase
#define IntegerBase iTidy_IntegerBase
#define LabelBase iTidy_LabelBase
#define ClickTabBase iTidy_ClickTabBase
#define SpaceBase iTidy_SpaceBase

#include "advanced_window.h"

#include <exec/types.h>
#include <exec/memory.h>
#include <intuition/intuition.h>
#include <intuition/screens.h>
#include <libraries/gadtools.h>
#include <proto/exec.h>
#include <proto/intuition.h>
#include <proto/gadtools.h>
#include <proto/graphics.h>
#include <proto/utility.h>
#include <clib/alib_protos.h>  /* Critical for BOOPSI */
#include <reaction/reaction_macros.h> /* Required for RA_HandleInput/RA_OpenWindow macros */
#include "platform/platform.h" /* Memory tracking */

/* ReAction Classes */
#include <proto/window.h>
#include <proto/layout.h>
#include <proto/button.h>
#include <proto/checkbox.h>
#include <proto/chooser.h>
#include <proto/integer.h>
#include <proto/label.h>
#include <proto/clicktab.h>
#include <proto/space.h>
#include <classes/window.h>
#include <gadgets/layout.h>
#include <gadgets/button.h>
#include <gadgets/checkbox.h>
#include <gadgets/chooser.h>
#include <gadgets/integer.h>
#include <gadgets/clicktab.h>
#include <gadgets/space.h>
#include <images/label.h>

#include "writeLog.h"
#include <stdio.h>
#include <string.h>

#include "writeLog.h" // Assuming logging is available

/*------------------------------------------------------------------------*/
/* Library Bases (Prefixed to avoid collision)                            */
/*------------------------------------------------------------------------*/
/* NOTE: These match the macros defined at the top of the file. */
/* They are declared global (not static) to match the extern declarations */
/* generated by the system headers (aliased via macros). */

struct Library *iTidy_WindowBase = NULL;
struct Library *iTidy_LayoutBase = NULL;
struct Library *iTidy_ButtonBase = NULL;
struct Library *iTidy_CheckBoxBase = NULL;
struct Library *iTidy_ChooserBase = NULL;
struct Library *iTidy_IntegerBase = NULL;
struct Library *iTidy_LabelBase = NULL;
struct Library *iTidy_ClickTabBase = NULL;
struct Library *iTidy_SpaceBase = NULL;

/*------------------------------------------------------------------------*/
/* Internal Helper Prototypes                                             */
/*------------------------------------------------------------------------*/
static BOOL open_reaction_classes(void);
static void close_reaction_classes(void);
static struct List *make_chooser_list(STRPTR *labels);
static void free_chooser_list(struct List *list);
static struct List *make_clicktab_list(STRPTR *labels);
static void free_clicktab_list(struct List *list);
static void update_gadget_states(struct iTidyAdvancedWindow *adv_data);
static void save_settings_from_gadgets(struct iTidyAdvancedWindow *adv_data);

/* Labels for Choosers and ClickTabs (Static const) */
static STRPTR aspect_labels_str[] = { "Tall (0.75)", "Square (1.0)", "Compact (1.3)", "Classic (1)", "Wide (2.0)", NULL };
static STRPTR overflow_labels_str[] = { "Expand horizontally", "Expand vertically", "Expand both", NULL };
static STRPTR width_labels_str[] = { "Auto", "30%", "50%", "70%", "90%", "100%", NULL };
static STRPTR align_labels_str[] = { "Top", "Middle", "Bottom", NULL };
static STRPTR gap_labels_str[] = { "Small", "Medium", "Large", NULL };
static STRPTR tab_labels_str[] = { "Layout", "Density", "Limits", "Columns & groups", "Filters & misc", NULL };

/*------------------------------------------------------------------------*/
/* Implementation                                                         */
/*------------------------------------------------------------------------*/

BOOL open_itidy_advanced_window(struct iTidyAdvancedWindow *adv_data, 
                                LayoutPreferences *prefs)
{
    if (!adv_data || !prefs) return FALSE;

    /* Initialize data structure */
    adv_data->window = NULL;
    adv_data->window_obj = NULL;
    adv_data->prefs = prefs;
    adv_data->changes_accepted = FALSE;

    /* Debug: Check incoming preferences */
    log_info(LOG_GUI, "Opening Advanced Window. Prefs: Aspect=%d, IconsRow=%d/%d, Spacing=%d/%d\n",
             prefs->aspectRatio, prefs->minIconsPerRow, prefs->maxIconsPerRow,
             prefs->iconSpacingX, prefs->iconSpacingY);
    
    /* Open Reaction Classes */
    if (!open_reaction_classes()) {
        log_error(LOG_GUI, "Failed to open ReAction classes\n");
        return FALSE;
    }

    /* Create Lists */
    adv_data->aspect_labels = make_chooser_list(aspect_labels_str);
    adv_data->overflow_labels = make_chooser_list(overflow_labels_str);
    adv_data->width_labels = make_chooser_list(width_labels_str);
    adv_data->align_labels = make_chooser_list(align_labels_str);
    adv_data->gap_labels = make_chooser_list(gap_labels_str);
    adv_data->tab_labels = make_clicktab_list(tab_labels_str);

    /* Construct Window Object */
    /* MAPPING NOTE: We match the layout from Test/ReActon/testcode.c */
    
    /* Pre-calculate states for mapping */
    ULONG initial_min_icons = prefs->minIconsPerRow;
    if (initial_min_icons == 0) initial_min_icons = 2; // Default if 0
    
    BOOL auto_max = (prefs->maxIconsPerRow == 0);
    ULONG initial_max_icons = auto_max ? 10 : prefs->maxIconsPerRow; // Visual default if auto
    
    /* Map LayoutMode to Checkbox (Column layout) */
    BOOL column_layout = (prefs->layoutMode == LAYOUT_MODE_COLUMN);
    
    /* Map OverflowMode to Chooser Index */
    WORD overflow_idx = 0;
    if (prefs->overflowMode == OVERFLOW_HORIZONTAL) overflow_idx = 0;
    else if (prefs->overflowMode == OVERFLOW_VERTICAL) overflow_idx = 1;
    else overflow_idx = 2;

    /* Map Aspect Ratio Value to Preset Index */
    /* 750=0, 1000=1, 1300=2, 1600=3, 2000=4 */
    WORD aspect_idx = 4; // Default Wide
    int ar = prefs->aspectRatio;
    if (ar <= 875) aspect_idx = 0;      // ~750
    else if (ar <= 1150) aspect_idx = 1; // ~1000
    else if (ar <= 1450) aspect_idx = 2; // ~1300
    else if (ar <= 1800) aspect_idx = 3; // ~1600
    else aspect_idx = 4;                 // ~2000+

    /* Map Max Width Pct to Index */
    /* 0=Auto, 1=30, 2=50, 3=70, 4=90, 5=100 */
    WORD width_idx = 0;
    /* This logic needs to match old window's "get_max_width_pct_preset_index" */
    /* Assuming simple mapping for now based on labels: Auto, 30, 50, 70, 90, 100 */
    if (prefs->maxWindowWidthPct == 0) width_idx = 0;
    else if (prefs->maxWindowWidthPct <= 30) width_idx = 1;
    else if (prefs->maxWindowWidthPct <= 50) width_idx = 2;
    else if (prefs->maxWindowWidthPct <= 70) width_idx = 3;
    else if (prefs->maxWindowWidthPct <= 90) width_idx = 4;
    else width_idx = 5;

    /* Define hint info for gadget help (static so it persists) */
    static struct HintInfo hintInfo[] =
    {
        {ITIDY_ADV_GAID_ROOT_LAYOUT, -1, "", 0},
        {ITIDY_ADV_GAID_CLICKTAB, -1, "", 0},
        {ITIDY_ADV_GAID_TAB_LAYOUT, -1, "Overall layout behaviour: window shape, what happens when full, and vertical alignment.", 0},
        {ITIDY_ADV_GAID_ASPECT_CHOOSER, -1, "Sets the target width-to-height shape for drawer windows.", 0},
        {ITIDY_ADV_GAID_OVERFLOW_CHOOSER, -1, "Choose what iTidy does when a drawer has more icons than fit comfortably on screen.", 0},
        {ITIDY_ADV_GAID_VERT_ALIGN_CHOOSER, -1, "Sets how icons are aligned vertically when a row contains icons of different heights.", 0},
        {ITIDY_ADV_GAID_TAB_DENSITY, -1, "Controls icon spacing and how tightly icons are packed.", 0},
        {ITIDY_ADV_GAID_SPACING_X, -1, "Sets the horizontal gap between icons (in pixels).", 0},
        {ITIDY_ADV_GAID_SPACING_Y, -1, "Sets the vertical gap between icons (in pixels).", 0},
        {ITIDY_ADV_GAID_SPACE_DENSITY, -1, "", 0},
        {ITIDY_ADV_GAID_TAB_LIMITS, -1, "Sets minimum/maximum columns and limits how wide drawer windows may become.", 0},
        {ITIDY_ADV_GAID_MIN_ICONS_ROW, -1, "Minimum columns. Prevents drawers becoming one long vertical list.", 0},
        {ITIDY_ADV_GAID_AUTO_MAX_CHECK, -1, "When enabled (default), iTidy automatically chooses the maximum columns based on the window width.", 0},
        {ITIDY_ADV_GAID_MAX_ICONS_ROW, -1, "Maximum columns (used only when Auto-calc max icons is disabled).", 0},
        {ITIDY_ADV_GAID_MAX_WIDTH_CHOOSER, -1, "Limits how wide drawer windows may become (percentage of screen width).", 0},
        {ITIDY_ADV_GAID_TAB_COLUMNS_GROUPS, -1, "Column mode options, auto-fit behaviour, and spacing between grouped icon blocks.", 0},
        {ITIDY_ADV_GAID_COLUMN_LAYOUT_CHECK, -1, "When enabled, iTidy uses a column-based layout rather than free-flow positioning.", 0},
        {ITIDY_ADV_GAID_BLOCK_GAP_CHOOSER, -1, "Controls spacing between icon groups when using the 'Grouped by Type' order mode.", 0},
        {ITIDY_ADV_GAID_SPACE_COLUMNS, -1, "", 0},
        {ITIDY_ADV_GAID_TAB_FILTERS_MISC, -1, "Optional processing rules and compatibility tweaks (hidden folders, NewIcons borders, reverse sort).", 0},
        {ITIDY_ADV_GAID_SKIP_HIDDEN_CHECK, -1, "When enabled (default), iTidy skips folders without .info files during recursive processing.", 0},
        {ITIDY_ADV_GAID_STRIP_BORDERS_CHECK, -1, "Strips NewIcons borders during processing (requires icon.library v44+). This permanently modifies those icons.", 0},
        {ITIDY_ADV_GAID_REVERSE_SORT_CHECK, -1, "Reverses the current sort direction (Z->A, newest-first, or largest-first depending on sort mode).", 0},
        {ITIDY_ADV_GAID_OPTIMIZE_COLS_CHECK, -1, "When enabled (default), each column is sized to its widest icon instead of forcing all columns to the same width.", 0},
        {ITIDY_ADV_GAID_BUTTON_LAYOUT, -1, "", 0},
        {ITIDY_ADV_GAID_BUTTON_COL1, -1, "", 0},
        {ITIDY_ADV_GAID_BUTTON_COL2, -1, "", 0},
        {ITIDY_ADV_GAID_DEFAULTS_BUTTON, -1, "Resets these settings to defaults.", 0},
        {ITIDY_ADV_GAID_CANCEL_BUTTON, -1, "Discards changes and returns to the main window.", 0},
        {ITIDY_ADV_GAID_OK_BUTTON, -1, "Accepts changes and closes this window. Use the main window's \"Save\" menu item to write settings to disk.", 0},
        {-1, -1, NULL, 0}
    };

    adv_data->window_obj = NewObject(WINDOW_GetClass(), NULL,
        WA_Title, "iTidy - Advanced settings",
        WA_ScreenTitle, "iTidy - Advanced settings",
        WA_CustomScreen, adv_data->screen,
        WA_Left, 5,
        WA_Top, 20,
        WA_Width, 450,
        WA_Height, 100,
        WA_MinWidth, 100,
        WA_MinHeight, 80,
        WA_MaxWidth, 8192,
        WA_MaxHeight, 8192,
        WA_CloseGadget, TRUE,
        WA_DepthGadget, TRUE,
        WA_SizeGadget, TRUE,
        WA_DragBar, TRUE,
        WA_Activate, TRUE,
        WINDOW_HintInfo, hintInfo,
        WINDOW_GadgetHelp, TRUE,
        WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_MENUHELP | IDCMP_NEWSIZE | IDCMP_RAWKEY,
        WINDOW_Position, WPOS_CENTERWINDOW,
        WINDOW_ParentGroup, NewObject(LAYOUT_GetClass(), NULL,
            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
            LAYOUT_SpaceOuter, TRUE,
            LAYOUT_DeferLayout, TRUE,

            /* Root vertical layout */
            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_ROOT_LAYOUT] = NewObject(LAYOUT_GetClass(), NULL,
                GA_ID, ITIDY_ADV_GAID_ROOT_LAYOUT,
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                
                /* ClickTab Gadget */
                LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_CLICKTAB] = NewObject(CLICKTAB_GetClass(), NULL,
                    GA_ID, ITIDY_ADV_GAID_CLICKTAB,
                    GA_RelVerify, TRUE,
                    GA_TabCycle, TRUE,
                    CLICKTAB_Labels, adv_data->tab_labels,
                    CLICKTAB_Current, 0,
                    CLICKTAB_PageGroup, PageObject,
                        LAYOUT_DeferLayout, TRUE,
                        
                        /* Tab 1: Layout */
                        PAGE_Add, adv_data->gadgets[ITIDY_ADV_TAB_LAYOUT] = NewObject(LAYOUT_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_GAID_TAB_LAYOUT,
                            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                            LAYOUT_LeftSpacing, 2,
                            LAYOUT_RightSpacing, 2,
                            LAYOUT_TopSpacing, 2,
                            LAYOUT_BottomSpacing, 2,
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_ASPECT_CHOOSER] = NewObject(CHOOSER_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_ASPECT_CHOOSER,
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                CHOOSER_PopUp, TRUE,
                                CHOOSER_Selected, aspect_idx,
                                CHOOSER_AutoFit, TRUE,
                                CHOOSER_Labels, adv_data->aspect_labels,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Layout aspect", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_OVERFLOW_CHOOSER] = NewObject(CHOOSER_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_OVERFLOW_CHOOSER,
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                CHOOSER_PopUp, TRUE,
                                CHOOSER_Selected, overflow_idx,
                                CHOOSER_Labels, adv_data->overflow_labels,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "When full", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_VERT_ALIGN_CHOOSER] = NewObject(CHOOSER_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_VERT_ALIGN_CHOOSER,
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                CHOOSER_PopUp, TRUE,
                                CHOOSER_Selected, prefs->textAlignment,
                                CHOOSER_Labels, adv_data->align_labels,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Align vertically", TAG_END),
                        TAG_END),
                        
                        /* Tab 2: Density */
                        PAGE_Add, adv_data->gadgets[ITIDY_ADV_TAB_DENSITY] = NewObject(LAYOUT_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_GAID_TAB_DENSITY,
                            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                            LAYOUT_LeftSpacing, 2,
                            LAYOUT_RightSpacing, 2,
                            LAYOUT_TopSpacing, 2,
                            LAYOUT_BottomSpacing, 2,
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_SPACING_X] = NewObject(INTEGER_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_SPACING_X,
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                INTEGER_Minimum, 0,
                                INTEGER_Maximum, 20,
                                INTEGER_Number, prefs->iconSpacingX,
                                INTEGER_MinVisible, 10,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Horizontal spacing", TAG_END),
                            CHILD_NominalSize, TRUE,
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_SPACING_Y] = NewObject(INTEGER_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_SPACING_Y,
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                INTEGER_MaxChars, 2,
                                INTEGER_Minimum, 0,
                                INTEGER_Maximum, 20,
                                INTEGER_Number, prefs->iconSpacingY,
                                INTEGER_MinVisible, 2,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Vertical spacing", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_SPACE_DENSITY] = NewObject(SPACE_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_SPACE_DENSITY,
                            TAG_END),
                        TAG_END),
                        
                        /* Tab 3: Limits */
                        PAGE_Add, adv_data->gadgets[ITIDY_ADV_TAB_LIMITS] = NewObject(LAYOUT_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_GAID_TAB_LIMITS,
                            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                            LAYOUT_LeftSpacing, 2,
                            LAYOUT_RightSpacing, 2,
                            LAYOUT_TopSpacing, 2,
                            LAYOUT_BottomSpacing, 2,
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_MIN_ICONS_ROW] = NewObject(INTEGER_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_MIN_ICONS_ROW,
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                INTEGER_Minimum, 0,
                                INTEGER_Maximum, 30,
                                INTEGER_Number, initial_min_icons,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Icons per row: Min", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_AUTO_MAX_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_AUTO_MAX_CHECK,
                                GA_Text, "",
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                GA_Selected, auto_max,
                                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Auto-calc max icons", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_MAX_ICONS_ROW] = NewObject(INTEGER_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_MAX_ICONS_ROW,
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                GA_Disabled, auto_max,
                                INTEGER_Minimum, 2,
                                INTEGER_Maximum, 40,
                                INTEGER_Number, initial_max_icons,
                                INTEGER_Arrows, FALSE,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Max", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_MAX_WIDTH_CHOOSER] = NewObject(CHOOSER_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_MAX_WIDTH_CHOOSER,
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                CHOOSER_PopUp, TRUE,
                                CHOOSER_Selected, width_idx,
                                CHOOSER_Labels, adv_data->width_labels,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Max window width", TAG_END),
                        TAG_END),
                        
                        /* Tab 4: Columns & groups */
                        PAGE_Add, adv_data->gadgets[ITIDY_ADV_TAB_COLUMNS_GROUPS] = NewObject(LAYOUT_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_GAID_TAB_COLUMNS_GROUPS,
                            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                            LAYOUT_LeftSpacing, 2,
                            LAYOUT_RightSpacing, 2,
                            LAYOUT_TopSpacing, 2,
                            LAYOUT_BottomSpacing, 2,
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_COLUMN_LAYOUT_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_COLUMN_LAYOUT_CHECK,
                                GA_Text, "",
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                GA_Selected, column_layout,
                                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Column layout", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_BLOCK_GAP_CHOOSER] = NewObject(CHOOSER_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_BLOCK_GAP_CHOOSER,
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                CHOOSER_PopUp, TRUE,
                                CHOOSER_Selected, prefs->blockGapSize,
                                CHOOSER_Labels, adv_data->gap_labels,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Gap between groups", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_SPACE_COLUMNS] = NewObject(SPACE_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_SPACE_COLUMNS,
                            TAG_END),
                        TAG_END),
                        
                        /* Tab 5: Filters & misc */
                        PAGE_Add, adv_data->gadgets[ITIDY_ADV_TAB_FILTERS_MISC] = NewObject(LAYOUT_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_GAID_TAB_FILTERS_MISC,
                            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                            LAYOUT_LeftSpacing, 2,
                            LAYOUT_RightSpacing, 2,
                            LAYOUT_TopSpacing, 2,
                            LAYOUT_BottomSpacing, 2,
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_SKIP_HIDDEN_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_SKIP_HIDDEN_CHECK,
                                GA_Text, "",
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                GA_Selected, prefs->skipHiddenFolders,
                                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Skip hidden folders", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_STRIP_BORDERS_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_STRIP_BORDERS_CHECK,
                                GA_Text, "",
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                GA_Selected, prefs->stripNewIconBorders,
                                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Strip NewIcons borders (permanent)", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_REVERSE_SORT_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_REVERSE_SORT_CHECK,
                                GA_Text, "",
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                GA_Selected, prefs->reverseSort,
                                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Reverse sort order", TAG_END),
                            
                            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_OPTIMIZE_COLS_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                                GA_ID, ITIDY_ADV_GAID_OPTIMIZE_COLS_CHECK,
                                GA_Text, "",
                                GA_RelVerify, TRUE,
                                GA_TabCycle, TRUE,
                                GA_Selected, prefs->useColumnWidthOptimization,
                                CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                            TAG_END),
                            CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Auto-fit columns", TAG_END),
                        TAG_END),
                    PageEnd,
                TAG_END),
                CHILD_WeightedHeight, 95,
                
                /* Buttons (Bottom) */
                LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_BUTTON_LAYOUT] = NewObject(LAYOUT_GetClass(), NULL,
                    GA_ID, ITIDY_ADV_GAID_BUTTON_LAYOUT,
                    LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
                    LAYOUT_LeftSpacing, 2,
                    LAYOUT_RightSpacing, 2,
                    LAYOUT_TopSpacing, 4,
                    LAYOUT_BottomSpacing, 2,
                    
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_BUTTON_COL1] = NewObject(LAYOUT_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_GAID_BUTTON_COL1,
                        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                    TAG_END),
                    CHILD_WeightedWidth, 50,
                    
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_BUTTON_COL2] = NewObject(LAYOUT_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_GAID_BUTTON_COL2,
                        LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
                        
                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_DEFAULTS_BUTTON] = NewObject(BUTTON_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_GAID_DEFAULTS_BUTTON,
                            GA_Text, "Defaults",
                            GA_RelVerify, TRUE,
                            GA_TabCycle, TRUE,
                            BUTTON_TextPen, 1,
                            BUTTON_BackgroundPen, 0,
                            BUTTON_FillTextPen, 1,
                            BUTTON_FillPen, 3,
                        TAG_END),
                        
                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_CANCEL_BUTTON] = NewObject(BUTTON_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_GAID_CANCEL_BUTTON,
                            GA_Text, "Cancel",
                            GA_RelVerify, TRUE,
                            GA_TabCycle, TRUE,
                            BUTTON_TextPen, 1,
                            BUTTON_BackgroundPen, 0,
                            BUTTON_FillTextPen, 1,
                            BUTTON_FillPen, 3,
                        TAG_END),
                        
                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_OK_BUTTON] = NewObject(BUTTON_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_GAID_OK_BUTTON,
                            GA_Text, "OK",
                            GA_RelVerify, TRUE,
                            GA_TabCycle, TRUE,
                            BUTTON_TextPen, 1,
                            BUTTON_BackgroundPen, 0,
                            BUTTON_FillTextPen, 1,
                            BUTTON_FillPen, 3,
                        TAG_END),
                    TAG_END),
                    CHILD_WeightedWidth, 50,
                TAG_END),
                CHILD_WeightedHeight, 5,
            TAG_END), // End Root Layout
        TAG_END), // End Parent Group
    TAG_END);

    if (adv_data->window_obj)
    {
        /* Open the window */
        if (adv_data->window = (struct Window *)RA_OpenWindow(adv_data->window_obj))
        {
            adv_data->window_open = TRUE;
            return TRUE;
        }
    }

    /* Cleanup if failed */
    if (adv_data->window_obj) DisposeObject(adv_data->window_obj);
    adv_data->window_obj = NULL;
    return FALSE;
}

void close_itidy_advanced_window(struct iTidyAdvancedWindow *adv_data)
{
    if (!adv_data) return;

    if (adv_data->window_obj)
    {
        DisposeObject(adv_data->window_obj); /* Automatically closes window and frees gadgets */
        adv_data->window_obj = NULL;
        adv_data->window = NULL;
        adv_data->window_open = FALSE;
    }

    /* Free Lists */
    if (adv_data->aspect_labels) { free_chooser_list(adv_data->aspect_labels); adv_data->aspect_labels = NULL; }
    if (adv_data->overflow_labels) { free_chooser_list(adv_data->overflow_labels); adv_data->overflow_labels = NULL; }
    if (adv_data->width_labels) { free_chooser_list(adv_data->width_labels); adv_data->width_labels = NULL; }
    if (adv_data->align_labels) { free_chooser_list(adv_data->align_labels); adv_data->align_labels = NULL; }
    if (adv_data->gap_labels) { free_chooser_list(adv_data->gap_labels); adv_data->gap_labels = NULL; }
    if (adv_data->tab_labels) { free_clicktab_list(adv_data->tab_labels); adv_data->tab_labels = NULL; }

    close_reaction_classes();
}

void handle_itidy_advanced_window_events(struct iTidyAdvancedWindow *adv_data)
{
    if (!adv_data || !adv_data->window_obj || !adv_data->window_open) return;

    ULONG result, code;
    BOOL done = FALSE;

    /* Initialize state variables from widgets or prefs to ensure consistency */
    adv_data->auto_max_enabled = (adv_data->prefs->maxIconsPerRow == 0); 

    while (!done)
    {
        /* Wait for input - RA_HandleInput returns WMHI_LASTMSG when queue is empty */
        while ((result = RA_HandleInput(adv_data->window_obj, &code)) != WMHI_LASTMSG)
        {
            switch (result & WMHI_CLASSMASK)
            {
                case WMHI_CLOSEWINDOW:
                    adv_data->changes_accepted = FALSE;
                    done = TRUE;
                    break;

                case WMHI_GADGETUP:
                    switch (result & WMHI_GADGETMASK)
                    {
                        case ITIDY_ADV_GAID_OK_BUTTON:
                            save_settings_from_gadgets(adv_data);
                            adv_data->changes_accepted = TRUE;
                            done = TRUE;
                            break;

                        case ITIDY_ADV_GAID_CANCEL_BUTTON:
                            adv_data->changes_accepted = FALSE;
                            done = TRUE;
                            break;
                            
                        case ITIDY_ADV_GAID_DEFAULTS_BUTTON:
                            /* TODO: Reset all settings to defaults */
                            /* This would require reloading default preferences and updating all gadgets */
                            log_info(LOG_GUI, "Defaults button clicked (not yet implemented)\n");
                            break;
                            
                        case ITIDY_ADV_GAID_CLICKTAB:
                            /* Tab switching is handled automatically by CLICKTAB_PageGroup */
                            break;
                            
                        case ITIDY_ADV_GAID_AUTO_MAX_CHECK:
                            /* Toggle the enabled state of the Max Icons gadget */
                            update_gadget_states(adv_data);
                            break;
                    }
                    break;
                    
                case WMHI_RAWKEY:
                    if (code == 0x45) // ESC key
                    {
                        adv_data->changes_accepted = FALSE;
                        done = TRUE;
                    }
                    break;
            }
        }
    }
}

/*------------------------------------------------------------------------*/
/* Helper Functions                                                       */
/*------------------------------------------------------------------------*/

static void update_gadget_states(struct iTidyAdvancedWindow *adv_data)
{
    ULONG selected = 0;
    
    /* Check Auto Max Checkbox state */
    GetAttr(CHECKBOX_Checked, adv_data->gadgets[ITIDY_ADV_AUTO_MAX_CHECK], &selected);
    adv_data->auto_max_enabled = (BOOL)selected;
    
    /* Enable/Disable Max Icons integer gadget based on checkbox */
    SetGadgetAttrs((struct Gadget *)adv_data->gadgets[ITIDY_ADV_MAX_ICONS_ROW], adv_data->window, NULL,
        GA_Disabled, adv_data->auto_max_enabled,
        TAG_END);
}

static const int aspect_ratio_presets[] = { 750, 1000, 1300, 1600, 2000, 2400 };

/* Safe getter for Integer gadgets (handles NULL) */
static ULONG get_integer_val(Object *obj)
{
    ULONG val = 0;
    GetAttr(INTEGER_Number, obj, &val);
    return val; 
}

/* Safe getter for Chooser/Checkbox gadgets (handles NULL) */
static ULONG get_choice_val(Object *obj)
{
    ULONG val = 0;
    GetAttr(CHOOSER_Selected, obj, &val); /* Works for GA_Selected too usually, but let's be safe */
    /* Checkbox uses GA_Selected (CHECKBOX_Checked deprecated but alias) */
    if (val > 65535) val = 0; /* Sanity check for -1 */
    return val;
}

static ULONG get_checkbox_val(Object *obj)
{
    ULONG val = 0;
    GetAttr(GA_Selected, obj, &val);
    return val;
}

static void save_settings_from_gadgets(struct iTidyAdvancedWindow *adv_data)
{
    if (!adv_data || !adv_data->prefs) return;
    LayoutPreferences *prefs = adv_data->prefs;

    /* Aspect Ratio: Map Index -> Value */
    ULONG idx = get_choice_val(adv_data->gadgets[ITIDY_ADV_ASPECT_CHOOSER]);
    if (idx < 6) prefs->aspectRatio = aspect_ratio_presets[idx];
    else prefs->aspectRatio = 2000; /* Default Wide */

    /* Overflow Mode */
    idx = get_choice_val(adv_data->gadgets[ITIDY_ADV_OVERFLOW_CHOOSER]);
    prefs->overflowMode = (WindowOverflowMode)idx;

    /* Icon Spacing */
    prefs->iconSpacingX = (UWORD)get_integer_val(adv_data->gadgets[ITIDY_ADV_SPACING_X]);
    prefs->iconSpacingY = (UWORD)get_integer_val(adv_data->gadgets[ITIDY_ADV_SPACING_Y]);

    /* Icons Per Row */
    prefs->minIconsPerRow = (UWORD)get_integer_val(adv_data->gadgets[ITIDY_ADV_MIN_ICONS_ROW]);
    
    /* Auto Max Checkbox */
    BOOL auto_max = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_AUTO_MAX_CHECK]);
    if (auto_max) {
        prefs->maxIconsPerRow = 0;
    } else {
        prefs->maxIconsPerRow = (UWORD)get_integer_val(adv_data->gadgets[ITIDY_ADV_MAX_ICONS_ROW]);
    }

    /* Max Window Width % */
    /* Map Index -> Value: 0=Auto(0), 1=30, 2=50, 3=70, 4=90, 5=100 */
    idx = get_choice_val(adv_data->gadgets[ITIDY_ADV_MAX_WIDTH_CHOOSER]);
    switch(idx) {
        case 0: prefs->maxWindowWidthPct = 0; break;
        case 1: prefs->maxWindowWidthPct = 30; break;
        case 2: prefs->maxWindowWidthPct = 50; break;
        case 3: prefs->maxWindowWidthPct = 70; break;
        case 4: prefs->maxWindowWidthPct = 90; break;
        case 5: prefs->maxWindowWidthPct = 100; break;
        default: prefs->maxWindowWidthPct = 0; break;
    }

    /* Vertical Align */
    prefs->textAlignment = (TextAlignment)get_choice_val(adv_data->gadgets[ITIDY_ADV_VERT_ALIGN_CHOOSER]);

    /* Checkboxes */
    prefs->reverseSort = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_REVERSE_SORT_CHECK]);
    prefs->useColumnWidthOptimization = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_OPTIMIZE_COLS_CHECK]);
    
    /* Column Layout (mapped to LayoutMode) */
    BOOL use_cols = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_COLUMN_LAYOUT_CHECK]);
    prefs->layoutMode = use_cols ? LAYOUT_MODE_COLUMN : LAYOUT_MODE_ROW;

    prefs->skipHiddenFolders = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_SKIP_HIDDEN_CHECK]);
    prefs->stripNewIconBorders = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_STRIP_BORDERS_CHECK]);

    /* Block Gap Size */
    prefs->blockGapSize = (BlockGapSize)get_choice_val(adv_data->gadgets[ITIDY_ADV_BLOCK_GAP_CHOOSER]);
}


static BOOL open_reaction_classes(void)
{
    /* Open classes with specific versions if needed, or 0 for any */
    if (!WindowBase) WindowBase = OpenLibrary("window.class", 0);
    if (!LayoutBase) LayoutBase = OpenLibrary("gadgets/layout.gadget", 0);
    if (!ButtonBase) ButtonBase = OpenLibrary("gadgets/button.gadget", 0);
    if (!CheckBoxBase) CheckBoxBase = OpenLibrary("gadgets/checkbox.gadget", 0);
    if (!ChooserBase) ChooserBase = OpenLibrary("gadgets/chooser.gadget", 0);
    if (!IntegerBase) IntegerBase = OpenLibrary("gadgets/integer.gadget", 0);
    if (!LabelBase) LabelBase = OpenLibrary("images/label.image", 0);
    if (!ClickTabBase) ClickTabBase = OpenLibrary("gadgets/clicktab.gadget", 0);
    if (!SpaceBase) SpaceBase = OpenLibrary("gadgets/space.gadget", 0);

    return (WindowBase && LayoutBase && ButtonBase && 
            CheckBoxBase && ChooserBase && IntegerBase && LabelBase &&
            ClickTabBase && SpaceBase);
}

static void close_reaction_classes(void)
{
    if (SpaceBase) { CloseLibrary(SpaceBase); SpaceBase = NULL; }
    if (ClickTabBase) { CloseLibrary(ClickTabBase); ClickTabBase = NULL; }
    if (LabelBase) { CloseLibrary(LabelBase); LabelBase = NULL; }
    if (IntegerBase) { CloseLibrary(IntegerBase); IntegerBase = NULL; }
    if (ChooserBase) { CloseLibrary(ChooserBase); ChooserBase = NULL; }
    if (CheckBoxBase) { CloseLibrary(CheckBoxBase); CheckBoxBase = NULL; }
    if (ButtonBase) { CloseLibrary(ButtonBase); ButtonBase = NULL; }
    if (LayoutBase) { CloseLibrary(LayoutBase); LayoutBase = NULL; }
    if (WindowBase) { CloseLibrary(WindowBase); WindowBase = NULL; }
}

static struct List *make_chooser_list(STRPTR *labels)
{
    struct List *list = (struct List *)whd_malloc(sizeof(struct List));
    if (list)
    {
        NewList(list);
        while (*labels)
        {
            struct Node *node = AllocChooserNode(CNA_Text, *labels, TAG_END);
            if (node)
            {
                AddTail(list, node);
            }
            labels++;
        }
    }
    return list;
}

static void free_chooser_list(struct List *list)
{
    if (list)
    {
        struct Node *node, *next;
        node = list->lh_Head;
        while ((next = node->ln_Succ))
        {
            FreeChooserNode(node);
            node = next;
        }
        whd_free(list);
    }
}

static struct List *make_clicktab_list(STRPTR *labels)
{
    struct List *list = (struct List *)whd_malloc(sizeof(struct List));
    if (list)
    {
        WORD tab_number = 0;
        NewList(list);
        while (*labels)
        {
            struct Node *node = AllocClickTabNode(TNA_Text, *labels, TNA_Number, tab_number, TAG_END);
            if (node)
            {
                AddTail(list, node);
            }
            labels++;
            tab_number++;
        }
    }
    return list;
}

static void free_clicktab_list(struct List *list)
{
    if (list)
    {
        struct Node *node, *next;
        node = list->lh_Head;
        while ((next = node->ln_Succ))
        {
            FreeClickTabNode(node);
            node = next;
        }
        whd_free(list);
    }
}
