/*
 * advanced_window_reaction.c - iTidy Advanced Settings Window (ReAction)
 * ReAction-based GUI for Workbench 3.2+
 */

/* Redefine library bases to local unique names BEFORE including proto headers */
/* This prevents collision with WindowBase defined in main_window.o */
/* The system headers declare 'extern struct Library *WindowBase', which the */
/* preprocessor will change to 'extern struct Library *iTidy_WindowBase'. */
#define WindowBase iTidy_WindowBase
#define LayoutBase iTidy_LayoutBase
#define ButtonBase iTidy_ButtonBase
#define CheckBoxBase iTidy_CheckBoxBase
#define ChooserBase iTidy_ChooserBase
#define IntegerBase iTidy_IntegerBase
#define LabelBase iTidy_LabelBase

#include "advanced_window.h"

#include <exec/types.h>
#include <exec/memory.h>
#include <intuition/intuition.h>
#include <intuition/screens.h>
#include <libraries/gadtools.h>
#include <proto/exec.h>
#include <proto/intuition.h>
#include <proto/gadtools.h>
#include <proto/graphics.h>
#include <proto/utility.h>
#include <clib/alib_protos.h>  /* Critical for BOOPSI */
#include <reaction/reaction_macros.h> /* Required for RA_HandleInput/RA_OpenWindow macros */
#include "platform/platform.h" /* Memory tracking */

/* ReAction Classes */
#include <proto/window.h>
#include <proto/layout.h>
#include <proto/button.h>
#include <proto/checkbox.h>
#include <proto/chooser.h>
#include <proto/integer.h>
#include <proto/label.h>
#include <classes/window.h>
#include <gadgets/layout.h>
#include <gadgets/button.h>
#include <gadgets/checkbox.h>
#include <gadgets/chooser.h>
#include <gadgets/integer.h>
#include <images/label.h>

#include "writeLog.h"
#include <stdio.h>
#include <string.h>

#include "writeLog.h" // Assuming logging is available

/*------------------------------------------------------------------------*/
/* Library Bases (Prefixed to avoid collision)                            */
/*------------------------------------------------------------------------*/
/* NOTE: These match the macros defined at the top of the file. */
/* They are declared global (not static) to match the extern declarations */
/* generated by the system headers (aliased via macros). */

struct Library *iTidy_WindowBase = NULL;
struct Library *iTidy_LayoutBase = NULL;
struct Library *iTidy_ButtonBase = NULL;
struct Library *iTidy_CheckBoxBase = NULL;
struct Library *iTidy_ChooserBase = NULL;
struct Library *iTidy_IntegerBase = NULL;
struct Library *iTidy_LabelBase = NULL;

/*------------------------------------------------------------------------*/
/* Internal Helper Prototypes                                             */
/*------------------------------------------------------------------------*/
static BOOL open_reaction_classes(void);
static void close_reaction_classes(void);
static struct List *make_chooser_list(STRPTR *labels);
static void free_chooser_list(struct List *list);
static void update_gadget_states(struct iTidyAdvancedWindow *adv_data);
static void save_settings_from_gadgets(struct iTidyAdvancedWindow *adv_data);

/* Labels for Choosers (Static const) */
static STRPTR aspect_labels_str[] = { "Tall (0.75)", "Square (1.0)", "Compact (1.3)", "Classic (1)", "Wide (2.0)", NULL };
static STRPTR overflow_labels_str[] = { "Expand horizontally", "Expand vertically", "Expand both", NULL };
static STRPTR width_labels_str[] = { "Auto", "30%", "50%", "70%", "90%", "100%", NULL };
static STRPTR align_labels_str[] = { "Top", "Middle", "Bottom", NULL };
static STRPTR gap_labels_str[] = { "Small", "Medium", "Large", NULL };

/*------------------------------------------------------------------------*/
/* Implementation                                                         */
/*------------------------------------------------------------------------*/

BOOL open_itidy_advanced_window(struct iTidyAdvancedWindow *adv_data, 
                                LayoutPreferences *prefs)
{
    if (!adv_data || !prefs) return FALSE;

    /* Initialize data structure */
    adv_data->window = NULL;
    adv_data->window_obj = NULL;
    adv_data->prefs = prefs;
    adv_data->changes_accepted = FALSE;

    /* Debug: Check incoming preferences */
    log_info(LOG_GUI, "Opening Advanced Window. Prefs: Aspect=%d, IconsRow=%d/%d, Spacing=%d/%d\n",
             prefs->aspectRatio, prefs->minIconsPerRow, prefs->maxIconsPerRow,
             prefs->iconSpacingX, prefs->iconSpacingY);
    
    /* Open Reaction Classes */
    if (!open_reaction_classes()) {
        log_error(LOG_GUI, "Failed to open ReAction classes\n");
        return FALSE;
    }

    /* Create Lists */
    adv_data->aspect_labels = make_chooser_list(aspect_labels_str);
    adv_data->overflow_labels = make_chooser_list(overflow_labels_str);
    adv_data->width_labels = make_chooser_list(width_labels_str);
    adv_data->align_labels = make_chooser_list(align_labels_str);
    adv_data->gap_labels = make_chooser_list(gap_labels_str);

    /* Construct Window Object */
    /* MAPPING NOTE: We match the layout from Test/ReActon/testcode.c */
    
    /* Pre-calculate states for mapping */
    ULONG initial_min_icons = prefs->minIconsPerRow;
    if (initial_min_icons == 0) initial_min_icons = 2; // Default if 0
    
    BOOL auto_max = (prefs->maxIconsPerRow == 0);
    ULONG initial_max_icons = auto_max ? 10 : prefs->maxIconsPerRow; // Visual default if auto
    
    /* Map LayoutMode to Checkbox (Column layout) */
    BOOL column_layout = (prefs->layoutMode == LAYOUT_MODE_COLUMN);
    
    /* Map OverflowMode to Chooser Index */
    WORD overflow_idx = 0;
    if (prefs->overflowMode == OVERFLOW_HORIZONTAL) overflow_idx = 0;
    else if (prefs->overflowMode == OVERFLOW_VERTICAL) overflow_idx = 1;
    else overflow_idx = 2;

    /* Map Aspect Ratio Value to Preset Index */
    /* 750=0, 1000=1, 1300=2, 1600=3, 2000=4 */
    WORD aspect_idx = 4; // Default Wide
    int ar = prefs->aspectRatio;
    if (ar <= 875) aspect_idx = 0;      // ~750
    else if (ar <= 1150) aspect_idx = 1; // ~1000
    else if (ar <= 1450) aspect_idx = 2; // ~1300
    else if (ar <= 1800) aspect_idx = 3; // ~1600
    else aspect_idx = 4;                 // ~2000+

    /* Map Max Width Pct to Index */
    /* 0=Auto, 1=30, 2=50, 3=70, 4=90, 5=100 */
    WORD width_idx = 0;
    /* This logic needs to match old window's "get_max_width_pct_preset_index" */
    /* Assuming simple mapping for now based on labels: Auto, 30, 50, 70, 90, 100 */
    if (prefs->maxWindowWidthPct == 0) width_idx = 0;
    else if (prefs->maxWindowWidthPct <= 30) width_idx = 1;
    else if (prefs->maxWindowWidthPct <= 50) width_idx = 2;
    else if (prefs->maxWindowWidthPct <= 70) width_idx = 3;
    else if (prefs->maxWindowWidthPct <= 90) width_idx = 4;
    else width_idx = 5;

    adv_data->window_obj = NewObject(WINDOW_GetClass(), NULL,
        WA_Title, "iTidy - Advanced Settings",
        WA_ScreenTitle, "iTidy - Advanced Settings",
        WA_CustomScreen, adv_data->screen,
        WA_Left, 5,
        WA_Top, 20,
        WA_Width, 300,
        WA_Height, 200,
        WA_MinWidth, 150,
        WA_MinHeight, 80,
        WA_MaxWidth, 8192,
        WA_MaxHeight, 8192,
        WA_CloseGadget, TRUE,
        WA_DepthGadget, TRUE,
        WA_SizeGadget, TRUE,
        WA_DragBar, TRUE,
        WA_Activate, TRUE,
        WA_IDCMP, IDCMP_GADGETDOWN | IDCMP_GADGETUP | IDCMP_CLOSEWINDOW | IDCMP_NEWSIZE | IDCMP_RAWKEY,
        WINDOW_Position, WPOS_CENTERWINDOW,
        WINDOW_ParentGroup, NewObject(LAYOUT_GetClass(), NULL,
            LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
            LAYOUT_SpaceOuter, TRUE,
            LAYOUT_DeferLayout, TRUE,

            /* Root vertical layout */
            LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_ROOT_LAYOUT] = NewObject(LAYOUT_GetClass(), NULL,
                GA_ID, ITIDY_ADV_ROOT_LAYOUT,
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                
                /* Layout Aspect & Overflow (Row 1) */
                LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_ROW_DETAILS] = NewObject(LAYOUT_GetClass(), NULL,
                    GA_ID, ITIDY_ADV_ROW_DETAILS,
                    LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
                    LAYOUT_TopSpacing, 4,
                    
                    /* Aspect Ratio Chooser */
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_ASPECT_GROUP] = NewObject(LAYOUT_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_ASPECT_GROUP,
                        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_ASPECT_CHOOSER] = NewObject(CHOOSER_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_ASPECT_CHOOSER,
                            GA_RelVerify, TRUE,
                            GA_TabCycle, TRUE,
                            CHOOSER_PopUp, TRUE,
                            CHOOSER_Selected, aspect_idx,
                            CHOOSER_Labels, adv_data->aspect_labels,
                        TAG_END),
                        CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Layout aspect", TAG_END),
                        
                        /* Overflow Mode */
                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_OVERFLOW_CHOOSER] = NewObject(CHOOSER_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_OVERFLOW_CHOOSER,
                            GA_RelVerify, TRUE,
                            GA_TabCycle, TRUE,
                            CHOOSER_PopUp, TRUE,
                            CHOOSER_Selected, overflow_idx,
                            CHOOSER_Labels, adv_data->overflow_labels,
                        TAG_END),
                        CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "When full:", TAG_END),
                    TAG_END),
                    
                    /* Icon Spacing Group */
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_SPACING_GROUP] = NewObject(LAYOUT_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_SPACING_GROUP,
                        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                        LAYOUT_Label, "Icon spacing",
                        
                        /* Spacing X */
                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_SPACING_X] = NewObject(INTEGER_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_SPACING_X,
                            GA_RelVerify, TRUE,
                            GA_TabCycle, TRUE,
                            INTEGER_Minimum, 0,
                            INTEGER_Maximum, 20, /* Check constraints */
                            INTEGER_Number, prefs->iconSpacingX,
                        TAG_END),
                        CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Spacing: X", TAG_END),

                        /* Spacing Y */
                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_SPACING_Y] = NewObject(INTEGER_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_SPACING_Y,
                            GA_RelVerify, TRUE,
                            GA_TabCycle, TRUE,
                            INTEGER_Minimum, 0,
                            INTEGER_Maximum, 20,
                            INTEGER_Number, prefs->iconSpacingY,
                        TAG_END),
                        CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Y", TAG_END),
                    TAG_END),
                TAG_END), // End Row 1
                
                /* Row 2: Icons Per Row Configuration */
                LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_ICONS_ROW_GROUP] = NewObject(LAYOUT_GetClass(), NULL,
                    GA_ID, ITIDY_ADV_ICONS_ROW_GROUP,
                    LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
                    LAYOUT_TopSpacing, 4,
                    
                    /* Min Icons Check */
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_MIN_ICONS_ROW] = NewObject(INTEGER_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_MIN_ICONS_ROW,
                        GA_RelVerify, TRUE,
                        GA_TabCycle, TRUE,
                        INTEGER_Minimum, 1,
                        INTEGER_Maximum, 20,
                        INTEGER_Number, initial_min_icons,
                    TAG_END),
                    CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Icons per row: Min:", TAG_END),

                    /* Auto Max Checkbox */
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_AUTO_MAX_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_AUTO_MAX_CHECK,
                        GA_Text, "Auto max icons",
                        GA_RelVerify, TRUE,
                        GA_TabCycle, TRUE,
                        GA_Selected, auto_max,
                        CHECKBOX_TextPlace, PLACETEXT_LEFT,
                    TAG_END),
                    
                    /* Max Icons Check (Disabled if Auto) */
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_MAX_ICONS_ROW] = NewObject(INTEGER_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_MAX_ICONS_ROW,
                        GA_RelVerify, TRUE,
                        GA_TabCycle, TRUE,
                        GA_Disabled, auto_max,
                        INTEGER_Minimum, 1,
                        INTEGER_Maximum, 20,
                        INTEGER_Number, initial_max_icons,
                    TAG_END),
                    CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Max", TAG_END),
                TAG_END),

                /* Row 3: Width & Vertical Align */
                LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_WIDTH_VERT_GROUP] = NewObject(LAYOUT_GetClass(), NULL,
                    GA_ID, ITIDY_ADV_WIDTH_VERT_GROUP,
                    LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
                    LAYOUT_TopSpacing, 4,
                    
                    /* Max Window Width */
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_MAX_WIDTH_CHOOSER] = NewObject(CHOOSER_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_MAX_WIDTH_CHOOSER,
                        GA_RelVerify, TRUE,
                        GA_TabCycle, TRUE,
                        CHOOSER_PopUp, TRUE,
                        CHOOSER_Selected, width_idx,
                        CHOOSER_Labels, adv_data->width_labels,
                    TAG_END),
                    CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Max window width", TAG_END),

                    /* Vertical Align */
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_VERT_ALIGN_CHOOSER] = NewObject(CHOOSER_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_VERT_ALIGN_CHOOSER,
                        GA_RelVerify, TRUE,
                        GA_TabCycle, TRUE,
                        CHOOSER_PopUp, TRUE,
                        CHOOSER_Selected, prefs->textAlignment,
                        CHOOSER_Labels, adv_data->align_labels,
                    TAG_END),
                    CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Align icons vertically", TAG_END),
                TAG_END),

                /* Row 4: Checkbox Columns */
                LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_CHECKBOX_GROUP] = NewObject(LAYOUT_GetClass(), NULL,
                    GA_ID, ITIDY_ADV_CHECKBOX_GROUP,
                    LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
                    LAYOUT_TopSpacing, 4,
                    
                    /* Column 1 */
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_CHECKBOX_COL1] = NewObject(LAYOUT_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_CHECKBOX_COL1,
                        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                        
                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_REVERSE_SORT_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_REVERSE_SORT_CHECK,
                            GA_Text, "Reverse Sort (Z->A)",
                            GA_RelVerify, TRUE,
                            GA_Selected, prefs->reverseSort,
                            CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                        TAG_END),

                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_OPTIMIZE_COLS_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_OPTIMIZE_COLS_CHECK,
                            GA_Text, "Optimize column widths",
                            GA_RelVerify, TRUE,
                            GA_Selected, prefs->useColumnWidthOptimization,
                            CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                        TAG_END),
                        
                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_COLUMN_LAYOUT_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_COLUMN_LAYOUT_CHECK,
                            GA_Text, "Column Layout",
                            GA_RelVerify, TRUE,
                            GA_Selected, column_layout,
                            CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                        TAG_END),
                    TAG_END),

                    /* Column 2 */
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_CHECKBOX_COL2] = NewObject(LAYOUT_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_CHECKBOX_COL2,
                        LAYOUT_Orientation, LAYOUT_ORIENT_VERT,

                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_SKIP_HIDDEN_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_SKIP_HIDDEN_CHECK,
                            GA_Text, "Skip hidden folders",
                            GA_RelVerify, TRUE,
                            GA_Selected, prefs->skipHiddenFolders,
                            CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                        TAG_END),

                        LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_STRIP_BORDERS_CHECK] = NewObject(CHECKBOX_GetClass(), NULL,
                            GA_ID, ITIDY_ADV_STRIP_BORDERS_CHECK,
                            GA_Text, "Strip new icon borders",
                            GA_RelVerify, TRUE,
                            GA_Selected, prefs->stripNewIconBorders,
                            CHECKBOX_TextPlace, PLACETEXT_RIGHT,
                        TAG_END),
                    TAG_END),
                TAG_END),

                /* Row 5: Grouping Options */
                LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_GROUPING_LAYOUT] = NewObject(LAYOUT_GetClass(), NULL,
                    GA_ID, ITIDY_ADV_GROUPING_LAYOUT,
                    LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
                    LAYOUT_TopSpacing, 4,
                    
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_BLOCK_GAP_CHOOSER] = NewObject(CHOOSER_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_BLOCK_GAP_CHOOSER,
                        GA_RelVerify, TRUE,
                        GA_TabCycle, TRUE,
                        CHOOSER_PopUp, TRUE,
                        CHOOSER_Selected, prefs->blockGapSize,
                        CHOOSER_Labels, adv_data->gap_labels,
                    TAG_END),
                    CHILD_Label, NewObject(LABEL_GetClass(), NULL, LABEL_Text, "Gap between groups", TAG_END),
                TAG_END),

                /* Buttons (Bottom) */
                LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_BUTTON_LAYOUT] = NewObject(LAYOUT_GetClass(), NULL,
                    GA_ID, ITIDY_ADV_BUTTON_LAYOUT,
                    LAYOUT_Orientation, LAYOUT_ORIENT_HORIZ,
                    LAYOUT_TopSpacing, 8,
                    
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_OK_BUTTON] = NewObject(BUTTON_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_OK_BUTTON,
                        GA_Text, "_OK",
                        GA_RelVerify, TRUE,
                        BUTTON_TextPen, 1,
                        BUTTON_BackgroundPen, 0,
                        BUTTON_FillTextPen, 1,
                        BUTTON_FillPen, 3,
                    TAG_END),
                    
                    LAYOUT_AddChild, adv_data->gadgets[ITIDY_ADV_CANCEL_BUTTON] = NewObject(BUTTON_GetClass(), NULL,
                        GA_ID, ITIDY_ADV_CANCEL_BUTTON,
                        GA_Text, "_Cancel",
                        GA_RelVerify, TRUE,
                        BUTTON_TextPen, 1,
                        BUTTON_BackgroundPen, 0,
                        BUTTON_FillTextPen, 1,
                        BUTTON_FillPen, 3,
                    TAG_END),
                TAG_END),

            TAG_END), // End Root Layout
        TAG_END), // End Parent Group
    TAG_END);

    if (adv_data->window_obj)
    {
        /* Open the window */
        if (adv_data->window = (struct Window *)RA_OpenWindow(adv_data->window_obj))
        {
            adv_data->window_open = TRUE;
            return TRUE;
        }
    }

    /* Cleanup if failed */
    if (adv_data->window_obj) DisposeObject(adv_data->window_obj);
    adv_data->window_obj = NULL;
    return FALSE;
}

void close_itidy_advanced_window(struct iTidyAdvancedWindow *adv_data)
{
    if (!adv_data) return;

    if (adv_data->window_obj)
    {
        DisposeObject(adv_data->window_obj); /* Automatically closes window and frees gadgets */
        adv_data->window_obj = NULL;
        adv_data->window = NULL;
        adv_data->window_open = FALSE;
    }

    /* Free Lists */
    if (adv_data->aspect_labels) { free_chooser_list(adv_data->aspect_labels); adv_data->aspect_labels = NULL; }
    if (adv_data->overflow_labels) { free_chooser_list(adv_data->overflow_labels); adv_data->overflow_labels = NULL; }
    if (adv_data->width_labels) { free_chooser_list(adv_data->width_labels); adv_data->width_labels = NULL; }
    if (adv_data->align_labels) { free_chooser_list(adv_data->align_labels); adv_data->align_labels = NULL; }
    if (adv_data->gap_labels) { free_chooser_list(adv_data->gap_labels); adv_data->gap_labels = NULL; }

    close_reaction_classes();
}

void handle_itidy_advanced_window_events(struct iTidyAdvancedWindow *adv_data)
{
    if (!adv_data || !adv_data->window_obj || !adv_data->window_open) return;

    ULONG result, code;
    BOOL done = FALSE;

    /* Initialize state variables from widgets or prefs to ensure consistency */
    adv_data->auto_max_enabled = (adv_data->prefs->maxIconsPerRow == 0); 

    while (!done)
    {
        /* Wait for input */
        result = RA_HandleInput(adv_data->window_obj, &code);

        switch (result & WMHI_CLASSMASK)
        {
            case WMHI_CLOSEWINDOW:
                adv_data->changes_accepted = FALSE;
                done = TRUE;
                break;

            case WMHI_GADGETUP:
                switch (result & WMHI_GADGETMASK)
                {
                    case ITIDY_ADV_OK_BUTTON:
                        save_settings_from_gadgets(adv_data);
                        adv_data->changes_accepted = TRUE;
                        done = TRUE;
                        break;

                    case ITIDY_ADV_CANCEL_BUTTON:
                        adv_data->changes_accepted = FALSE;
                        done = TRUE;
                        break;
                        
                    case ITIDY_ADV_AUTO_MAX_CHECK:
                        /* Toggle the enabled state of the Max Icons gadget */
                        update_gadget_states(adv_data);
                        break;
                }
                break;
                
            case WMHI_RAWKEY:
                if (code == 0x45) // ESC key
                {
                    adv_data->changes_accepted = FALSE;
                    done = TRUE;
                }
                break;
        }
    }
}

/*------------------------------------------------------------------------*/
/* Helper Functions                                                       */
/*------------------------------------------------------------------------*/

static void update_gadget_states(struct iTidyAdvancedWindow *adv_data)
{
    ULONG selected = 0;
    
    /* Check Auto Max Checkbox state */
    GetAttr(CHECKBOX_Checked, adv_data->gadgets[ITIDY_ADV_AUTO_MAX_CHECK], &selected);
    adv_data->auto_max_enabled = (BOOL)selected;
    
    /* Enable/Disable Max Icons integer gadget based on checkbox */
    SetGadgetAttrs((struct Gadget *)adv_data->gadgets[ITIDY_ADV_MAX_ICONS_ROW], adv_data->window, NULL,
        GA_Disabled, adv_data->auto_max_enabled,
        TAG_END);
}

static const int aspect_ratio_presets[] = { 750, 1000, 1300, 1600, 2000, 2400 };

/* Safe getter for Integer gadgets (handles NULL) */
static ULONG get_integer_val(Object *obj)
{
    ULONG val = 0;
    GetAttr(INTEGER_Number, obj, &val);
    return val; 
}

/* Safe getter for Chooser/Checkbox gadgets (handles NULL) */
static ULONG get_choice_val(Object *obj)
{
    ULONG val = 0;
    GetAttr(CHOOSER_Selected, obj, &val); /* Works for GA_Selected too usually, but let's be safe */
    /* Checkbox uses GA_Selected (CHECKBOX_Checked deprecated but alias) */
    if (val > 65535) val = 0; /* Sanity check for -1 */
    return val;
}

static ULONG get_checkbox_val(Object *obj)
{
    ULONG val = 0;
    GetAttr(GA_Selected, obj, &val);
    return val;
}

static void save_settings_from_gadgets(struct iTidyAdvancedWindow *adv_data)
{
    if (!adv_data || !adv_data->prefs) return;
    LayoutPreferences *prefs = adv_data->prefs;

    /* Aspect Ratio: Map Index -> Value */
    ULONG idx = get_choice_val(adv_data->gadgets[ITIDY_ADV_ASPECT_CHOOSER]);
    if (idx < 6) prefs->aspectRatio = aspect_ratio_presets[idx];
    else prefs->aspectRatio = 2000; /* Default Wide */

    /* Overflow Mode */
    idx = get_choice_val(adv_data->gadgets[ITIDY_ADV_OVERFLOW_CHOOSER]);
    prefs->overflowMode = (WindowOverflowMode)idx;

    /* Icon Spacing */
    prefs->iconSpacingX = (UWORD)get_integer_val(adv_data->gadgets[ITIDY_ADV_SPACING_X]);
    prefs->iconSpacingY = (UWORD)get_integer_val(adv_data->gadgets[ITIDY_ADV_SPACING_Y]);

    /* Icons Per Row */
    prefs->minIconsPerRow = (UWORD)get_integer_val(adv_data->gadgets[ITIDY_ADV_MIN_ICONS_ROW]);
    
    /* Auto Max Checkbox */
    BOOL auto_max = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_AUTO_MAX_CHECK]);
    if (auto_max) {
        prefs->maxIconsPerRow = 0;
    } else {
        prefs->maxIconsPerRow = (UWORD)get_integer_val(adv_data->gadgets[ITIDY_ADV_MAX_ICONS_ROW]);
    }

    /* Max Window Width % */
    /* Map Index -> Value: 0=Auto(0), 1=30, 2=50, 3=70, 4=90, 5=100 */
    idx = get_choice_val(adv_data->gadgets[ITIDY_ADV_MAX_WIDTH_CHOOSER]);
    switch(idx) {
        case 0: prefs->maxWindowWidthPct = 0; break;
        case 1: prefs->maxWindowWidthPct = 30; break;
        case 2: prefs->maxWindowWidthPct = 50; break;
        case 3: prefs->maxWindowWidthPct = 70; break;
        case 4: prefs->maxWindowWidthPct = 90; break;
        case 5: prefs->maxWindowWidthPct = 100; break;
        default: prefs->maxWindowWidthPct = 0; break;
    }

    /* Vertical Align */
    prefs->textAlignment = (TextAlignment)get_choice_val(adv_data->gadgets[ITIDY_ADV_VERT_ALIGN_CHOOSER]);

    /* Checkboxes */
    prefs->reverseSort = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_REVERSE_SORT_CHECK]);
    prefs->useColumnWidthOptimization = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_OPTIMIZE_COLS_CHECK]);
    
    /* Column Layout (mapped to LayoutMode) */
    BOOL use_cols = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_COLUMN_LAYOUT_CHECK]);
    prefs->layoutMode = use_cols ? LAYOUT_MODE_COLUMN : LAYOUT_MODE_ROW;

    prefs->skipHiddenFolders = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_SKIP_HIDDEN_CHECK]);
    prefs->stripNewIconBorders = (BOOL)get_checkbox_val(adv_data->gadgets[ITIDY_ADV_STRIP_BORDERS_CHECK]);

    /* Block Gap Size */
    prefs->blockGapSize = (BlockGapSize)get_choice_val(adv_data->gadgets[ITIDY_ADV_BLOCK_GAP_CHOOSER]);
}


static BOOL open_reaction_classes(void)
{
    /* Open classes with specific versions if needed, or 0 for any */
    if (!WindowBase) WindowBase = OpenLibrary("window.class", 0);
    if (!LayoutBase) LayoutBase = OpenLibrary("gadgets/layout.gadget", 0);
    if (!ButtonBase) ButtonBase = OpenLibrary("gadgets/button.gadget", 0);
    if (!CheckBoxBase) CheckBoxBase = OpenLibrary("gadgets/checkbox.gadget", 0);
    if (!ChooserBase) ChooserBase = OpenLibrary("gadgets/chooser.gadget", 0);
    if (!IntegerBase) IntegerBase = OpenLibrary("gadgets/integer.gadget", 0);
    if (!LabelBase) LabelBase = OpenLibrary("images/label.image", 0);

    return (WindowBase && LayoutBase && ButtonBase && 
            CheckBoxBase && ChooserBase && IntegerBase && LabelBase);
}

static void close_reaction_classes(void)
{
    if (LabelBase) { CloseLibrary(LabelBase); LabelBase = NULL; }
    if (IntegerBase) { CloseLibrary(IntegerBase); IntegerBase = NULL; }
    if (ChooserBase) { CloseLibrary(ChooserBase); ChooserBase = NULL; }
    if (CheckBoxBase) { CloseLibrary(CheckBoxBase); CheckBoxBase = NULL; }
    if (ButtonBase) { CloseLibrary(ButtonBase); ButtonBase = NULL; }
    if (LayoutBase) { CloseLibrary(LayoutBase); LayoutBase = NULL; }
    if (WindowBase) { CloseLibrary(WindowBase); WindowBase = NULL; }
}

static struct List *make_chooser_list(STRPTR *labels)
{
    struct List *list = (struct List *)whd_malloc(sizeof(struct List));
    if (list)
    {
        NewList(list);
        while (*labels)
        {
            struct Node *node = AllocChooserNode(CNA_Text, *labels, TAG_END);
            if (node)
            {
                AddTail(list, node);
            }
            labels++;
        }
    }
    return list;
}

static void free_chooser_list(struct List *list)
{
    if (list)
    {
        struct Node *node, *next;
        node = list->lh_Head;
        while ((next = node->ln_Succ))
        {
            FreeChooserNode(node);
            node = next;
        }
        whd_free(list);
    }
}
